Repository replicatedhq/troubleshoot, pull requests merged in 2022-11, with the labels that each got.

#819 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: type::feature, type::docs

#822 Add ADR directory and readme
  docs/arch/readme.md
Labels: type::feature, type::docs

#826 Update fossa
  .github/workflows/pr-license-scan.yaml
Labels: type::chore

#830 feat(github): add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type::feature

#831 chore: Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type::chore

#814 Add omitempty to StorageClassName in schema
  config/crds/troubleshoot.replicated.com_analyzers.yaml
  config/crds/troubleshoot.replicated.com_preflights.yaml
  config/crds/troubleshoot.replicated.com_supportbundles.yaml
  config/crds/troubleshoot.sh_analyzers.yaml
  config/crds/troubleshoot.sh_collectors.yaml
  config/crds/troubleshoot.sh_hostcollectors.yaml
  config/crds/troubleshoot.sh_hostpreflights.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  pkg/apis/troubleshoot/v1beta1/analyzer_shared.go
  pkg/apis/troubleshoot/v1beta2/analyzer_shared.go
  schemas/analyzer-troubleshoot-v1beta1.json
  schemas/analyzer-troubleshoot-v1beta2.json
  schemas/collector-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta1.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta1.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::bug, bug::normal

#823 docs: ADR-001 remove default redaction of IP addresses
  docs/arch/adr-001-ipaddress-redaction.md
Labels: type::feature

#833 correct checked out ref for FOSSA tests
  .github/workflows/pr-license-scan.yaml
Labels: type::chore

#810 Add proposal to consolidate collection code
  design/proposal-consolidate-collection.md
Labels: type::feature, type::docs

#840 Remove ingress check from https://preflight.replicated.com
  examples/preflight/sample-preflight.yaml
Labels: type::chore

#846 Revert "Remove ingress check from https://preflight.replicated.com"
  examples/preflight/sample-preflight.yaml
Labels: type::chore

#845 doc/readme : make clear that the links are just examples
  README.md
Labels: type::chore, type::docs

#848 Add ghcr to package releases
  Makefile
  deploy/.goreleaser.yaml
Labels: type::chore

#834 fix(flag): fix wrong output filename
  pkg/preflight/flags.go
  pkg/preflight/flags_test.go
Labels: type::bug, bug::regression

#851 Add job to dependabot to update github actions
  .github/dependabot.yml
Labels: type::chore

#858 docs: add ADR for mergable preflight specs
  docs/arch/adr-002-mergeable-preflights.md
Labels: type::feature

#862 feat: Add docsgen command
  Makefile
  cmd/docsgen/cli/root.go
  cmd/docsgen/main.go
  docs/preflight.md
  docs/preflight_version.md
  docs/support-bundle.md
  docs/support-bundle_analyze.md
  docs/support-bundle_version.md
  go.mod
  go.sum
Labels: type::feature

#821 feat(collectors): Store all pod logs in cluster-resources directory
  .gitignore
  examples/preflight/e2e.yaml
  examples/support-bundle/e2e.yaml
  examples/support-bundle/sample-supportbundle.yaml
  pkg/collect/cluster_resources.go
  pkg/collect/logs.go
  pkg/collect/logs_test.go
  pkg/collect/redact.go
  pkg/collect/remote_collector.go
  pkg/collect/result.go
  pkg/collect/run_pod.go
  pkg/supportbundle/collect.go
  pkg/supportbundle/supportbundle.go
  test/validate-preflight-e2e.sh
  test/validate-support-bundle-e2e.sh
Labels: type::feature

#868 Revert "Add ghcr to package releases (#848)"
  Makefile
  deploy/.goreleaser.yaml
Labels: type::chore

#867 feat(analyze): add ExcludeFiles field to textAnazlye
  config/crds/troubleshoot.sh_analyzers.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  pkg/analyze/analyzer.go
  pkg/analyze/cluster_pod_statuses.go
  pkg/analyze/deployment_status.go
  pkg/analyze/deployment_status_test.go
  pkg/analyze/download.go
  pkg/analyze/image_pull_secret.go
  pkg/analyze/job_status.go
  pkg/analyze/job_status_test.go
  pkg/analyze/longhorn.go
  pkg/analyze/replicaset_status.go
  pkg/analyze/replicaset_status_test.go
  pkg/analyze/statefulset_status.go
  pkg/analyze/statefulset_status_test.go
  pkg/analyze/sysctl.go
  pkg/analyze/sysctl_test.go
  pkg/analyze/text_analyze.go
  pkg/analyze/text_analyze_test.go
  pkg/analyze/weave.go
  pkg/analyze/weave_test.go
  pkg/apis/troubleshoot/v1beta2/analyzer_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  pkg/preflight/analyze.go
  schemas/analyzer-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::feature

#872 chore: Add GH workflow to ensure schemas are generated in a PR
  .github/workflows/build-test-deploy.yaml
  Makefile
  pkg/apis/troubleshoot/v1beta2/collector_shared.go
Labels: type::chore

#874 Includes virtual memory parameters in Sysctl
  pkg/analyze/sysctl.go
  pkg/analyze/sysctl_test.go
  pkg/collect/sysctl.go
Labels: type::feature

#734 remove IP address redaction
  pkg/redact/redact.go
  pkg/redact/redact_test.go
Labels: type::feature

#875 feat(collectors): Add TLS parameters to the postgres collector
  examples/preflight/postgres.yaml
  go.mod
  go.sum
  pkg/collect/postgres.go
  pkg/collect/postgres_test.go
Labels: type::feature
