Repository replicatedhq/troubleshoot, pull requests merged in 2022-07, with the labels that each got.

#615 Make sure to clean up resources when done including run pods
  pkg/collect/copy_from_host.go
  pkg/collect/run.go
  pkg/collect/run_pod.go
  pkg/collect/sysctl.go
Labels: type::bug, bug::normal

#626 add instructions to cross-compile with Go
  CONTRIBUTING.md
Labels: type::docs

#611 Proposal provide extendable API for bundle information
  design/proposal-standard-interface.md
  design/template.md
Labels: type::docs

#573 update go module github.com/mholt/archiver/v3
  go.mod
  go.sum
  pkg/supportbundle/parse.go
Labels: type::chore, team::blue
