Repository replicatedhq/troubleshoot, pull requests merged in 2022-06, with the labels that each got.

#585 Run e2e tests locally
  .github/workflows/build-test-deploy.yaml
  CONTRIBUTING.md
  Makefile
  test/validate-preflight-e2e.sh
Labels: type::chore

#586 remove redundant client-gen code generated in wrong path
  Makefile
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/clientset.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/doc.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/fake/clientset_generated.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/fake/doc.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/fake/register.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/scheme/doc.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/scheme/register.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/analyzer.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/collector.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/doc.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/doc.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_analyzer.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_collector.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_preflight.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_redactor.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_supportbundle.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_troubleshoot_client.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/generated_expansion.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/preflight.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/redactor.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/supportbundle.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/troubleshoot_client.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/analyzer.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/collector.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/doc.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/doc.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_analyzer.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_collector.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_hostcollector.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_hostpreflight.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_preflight.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_redactor.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_remotecollector.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_supportbundle.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_troubleshoot_client.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/generated_expansion.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/hostcollector.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/hostpreflight.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/preflight.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/redactor.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/remotecollector.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/supportbundle.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/troubleshoot_client.go
  pkg/client/troubleshootclientset/fake/clientset_generated.go
Labels: type::chore, team::blue

#591 Update Contributing.md
  CONTRIBUTING.md
Labels: type::chore

#592 Disable client-go logging
  cmd/analyze/cli/root.go
  cmd/collect/cli/root.go
  cmd/preflight/cli/root.go
  cmd/troubleshoot/cli/root.go
Labels: type::chore

#600 Wrapper function for analyzer's exclude flag
  pkg/apis/troubleshoot/v1beta2/analyzer_shared.go
Labels: type::feature, team::orange

#598 feat: adds new yamlCompare and jsonCompare analyzers
  pkg/analyze/analyzer.go
  pkg/analyze/json_compare.go
  pkg/analyze/json_compare_test.go
  pkg/analyze/yaml_compare.go
  pkg/analyze/yaml_compare_test.go
  pkg/apis/troubleshoot/v1beta2/analyzer_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  pkg/interfaceutils/interfaceutils.go
Labels: type::feature, team::orange

#601 Use reflection instead of hardcoding all alnalyzers
  pkg/analyze/analyzer.go
  pkg/analyze/analyzer_test.go
  pkg/apis/troubleshoot/v1beta2/analyzer_shared.go
Labels: bug::normal, team::orange

#605 Update K8s versions and container runtime
  examples/preflight/sample-preflight.yaml
Labels: type::chore

#610 Fix flaky Ceph analyzer test
  pkg/analyze/ceph_test.go
Labels: type::bug, bug::normal

#606 Host Run Collector
  pkg/apis/troubleshoot/v1beta2/hostcollector_shared.go
  pkg/collect/host_collector.go
  pkg/collect/host_run.go
Labels: type::feature
