Repository replicatedhq/troubleshoot, pull requests merged in 2022-03, with the labels that each got.

#543 Fix getting pod details for new support bundle formats
  pkg/supportbundle/parse.go
  pkg/supportbundle/parse_test.go
Labels: type::bug, bug::regression, team::orange

#544 Add ServiceAccountName parameter to Run collector
  pkg/apis/troubleshoot/v1beta2/collector_shared.go
  pkg/collect/run.go
Labels: type::feature

#551 map strict flag to analyze result
  pkg/preflight/analyze.go
  pkg/preflight/util.go
  pkg/preflight/util_test.go
Labels: type::bug, bug::regression, team::blue

#552 fix: return true when one of analyzers strict field is true
  pkg/preflight/analyze.go
  pkg/preflight/util.go
  pkg/preflight/util_test.go
Labels: type::bug, bug::regression

#554 pods with containers that are not 'ready' are unhealthy
  pkg/analyze/cluster_pod_statuses.go
  pkg/k8sutil/pod.go
  pkg/k8sutil/pod_test.go
Labels: type::bug, bug::normal, team::support
