Repository replicatedhq/troubleshoot, pull requests merged in 2022-05, with the labels that each got.

#563 Include osd disk usage
  pkg/collect/ceph.go
Labels: type::chore

#566 BoolOrString pollutes marshalling, does not respect omitempty
  pkg/analyze/analyzer.go
  pkg/apis/troubleshoot/v1beta1/analyzer_shared.go
  pkg/apis/troubleshoot/v1beta1/collector_shared.go
  pkg/apis/troubleshoot/v1beta1/zz_generated.deepcopy.go
  pkg/apis/troubleshoot/v1beta2/analyzer_shared.go
  pkg/apis/troubleshoot/v1beta2/collector_shared.go
  pkg/apis/troubleshoot/v1beta2/hostcollector_shared.go
  pkg/apis/troubleshoot/v1beta2/remote_collector_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  pkg/collect/collector.go
  pkg/collect/collector_test.go
  pkg/multitype/boolstring.go
  pkg/multitype/boolstring_test.go
  pkg/preflight/util_test.go
Labels: type::bug, bug::normal

#564 RunPod Collector
  pkg/apis/troubleshoot/v1beta2/collector_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  pkg/collect/collector.go
  pkg/collect/run.go
Labels: type::feature

#569 fix cve
  go.mod
  go.sum
  pkg/longhorn/util/util.go
Labels: type::security, team::blue

#572 add cve scan Github action
  .github/workflows/daily-scan.yaml
  Makefile
Labels: type::security, team::blue

#575 Ceph health status messages in Analzyer result
  pkg/analyze/ceph.go
  pkg/analyze/ceph_test.go
Labels: type::feature

#576 Fix run collector text analyze file path mismatch
  .github/workflows/build-test-deploy.yaml
  Makefile
  examples/preflight/e2e.yaml
  pkg/collect/run.go
  pkg/collect/run_pod.go
Labels: type::bug, bug::regression

#578 filter nil analyzer results to prevent panic
  pkg/analyze/download.go
  pkg/convert/supportbundle.go
Labels: type::bug, bug::normal

#580 Add support for k8s 1.24+
  pkg/analyze/distribution.go
  pkg/collect/copy_from_host.go
  pkg/collect/run_pod.go
Labels: type::feature

#581 fix panic: return nil result when no files to check deployment status analyzer
  pkg/analyze/deployment_status.go
Labels: type::bug, bug::regression, team::support
