Repository replicatedhq/troubleshoot, pull requests merged in 2022-09, with the labels that each got.

#696 EL 20220901 - Implement new type for #682
  config/samples/troubleshoot_v1beta2_collector.yaml
  pkg/apis/troubleshoot/v1beta2/supportbundle_types.go
Labels: type::feature

#683 Danj multiple inputs
  cmd/troubleshoot/cli/root.go
  cmd/troubleshoot/cli/run.go
  pkg/supportbundle/supportbundle.go
  pkg/supportbundle/supportbundle_test.go
  pkg/supportbundle/test/completebundle.yaml
  pkg/supportbundle/test/supportbundle1.yaml
  pkg/supportbundle/test/supportbundle2.yaml
Labels: type::feature

#704 Update issue template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: type::docs

#709 Load support bundle specs from secrets matching label selector
  cmd/troubleshoot/cli/root.go
  cmd/troubleshoot/cli/run.go
  pkg/specs/secrets.go
  pkg/specs/secrets_test.go
  pkg/supportbundle/load.go
  pkg/supportbundle/supportbundle_test.go
Labels: type::feature

#718 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: type::chore, type::docs

#721 Add gate to prevent attempt to run on fork
  .github/workflows/pr-license-scan.yaml
Labels: type::chore

#750 Fix concat spec for cluster secrets
  cmd/troubleshoot/cli/run.go
Labels: type::bug, bug::normal
