Repository replicatedhq/troubleshoot, pull requests merged in 2022-12, with the labels that each got.

#880 chore: Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type::chore

#886 fix(collectors): Fix logs collection in longhorn collector
  pkg/collect/ceph.go
  pkg/collect/logs.go
  pkg/collect/longhorn.go
  pkg/collect/result.go
  pkg/collect/result_test.go
Labels: type::bug

#832 Deduplication for Cluster Resources Collector
  pkg/collect/cluster_resources.go
  pkg/collect/cluster_resources_test.go
  pkg/preflight/collect.go
  pkg/supportbundle/collect.go
Labels: type::feature

#809 Add proposal for concurrent collection
  design/proposal-concurrent-collectors.md
Labels: type::feature

#896 chore: update containerd to v1.6.12
  go.mod
  go.sum
Labels: type::chore

#893 Add sbctl integration proposal and move design directory into docs
  docs/design/design-principles.md
  docs/design/proposal-consolidate-collection.md
  docs/design/proposal-mergeable-spec.md
  docs/design/proposal-sbctl-integration.md
  docs/design/proposal-standard-interface.md
  docs/design/proposal-updateable-specs.md
  docs/design/template.md
Labels: type::chore

#894 Allow Preflight CLI to consume multiple specs as input
  cmd/preflight/cli/root.go
  pkg/preflight/concat.go
  pkg/preflight/run.go
Labels: type::feature

#780 Add generic kubernetes resource analyzer
  config/crds/troubleshoot.sh_analyzers.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  pkg/analyze/analyzer.go
  pkg/analyze/files/support-bundle/cluster-resources/deployments/default.json
  pkg/analyze/files/support-bundle/cluster-resources/deployments/kube-system.json
  pkg/analyze/files/support-bundle/cluster-resources/deployments/monitoring.json
  pkg/analyze/files/support-bundle/cluster-resources/jobs/projectcontour.json
  pkg/analyze/files/support-bundle/cluster-resources/jobs/test.json
  pkg/analyze/files/support-bundle/cluster-resources/nodes.json
  pkg/analyze/files/support-bundle/cluster-resources/replicasets/default.json
  pkg/analyze/files/support-bundle/cluster-resources/replicasets/rook-ceph.json
  pkg/analyze/files/support-bundle/cluster-resources/statefulsets/default.json
  pkg/analyze/files/support-bundle/cluster-resources/statefulsets/monitoring.json
  pkg/analyze/kube_resource.go
  pkg/analyze/kube_resource_test.go
  pkg/apis/troubleshoot/v1beta2/analyzer_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  schemas/analyzer-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::feature

#924 Minor format change to README.md
  README.md
Labels: type::chore

#920 feat(cluster_resources): increase default client burst and qps
  pkg/constants/constants.go
  pkg/preflight/collect.go
  pkg/supportbundle/collect.go
Labels: type::bug, bug::normal

#918 rename the troubleshoot label to "support-bundle"
  cmd/troubleshoot/cli/root.go
  docs/support-bundle.md
  pkg/specs/configmaps_test.go
  pkg/specs/secrets_test.go
Labels: type::feature, echoes/effort: XS

#928 fix: collect rbac permissions error
  pkg/preflight/collect.go
Labels: type::bug, bug::regression

#927 chore: Upgrade gopsutil to v3
  go.mod
  go.sum
  pkg/collect/host_cpu.go
  pkg/collect/host_cpu_test.go
  pkg/collect/host_disk_usage.go
  pkg/collect/host_disk_usage_test.go
  pkg/collect/host_memory.go
  pkg/collect/host_memory_test.go
  pkg/collect/host_os_info.go
  pkg/collect/host_os_info_test.go
  pkg/collect/postgres_test.go
  pkg/collect/redis_test.go
  pkg/collect/util_test.go
  pkg/preflight/flags_test.go
Labels: type::chore

#932 If no pods are selected for log collector, do not wait for timeout
  pkg/collect/logs.go
Labels: type::bug, bug::regression

#930 add cpuArchitecture filter to nodeResources collector
  config/crds/troubleshoot.sh_analyzers.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  examples/preflight/node-resources.yaml
  pkg/analyze/node_resources.go
  pkg/analyze/node_resources_test.go
  pkg/apis/troubleshoot/v1beta2/analyzer_shared.go
  schemas/analyzer-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::feature, echoes/effort: S
