Repository replicatedhq/troubleshoot, pull requests merged in 2022-10, with the labels that each got.

#670 Refactor in-clusters collectors to use struct per collector
  cmd/preflight/cli/upload_results.go
  cmd/troubleshoot/cli/run.go
  pkg/collect/ceph.go
  pkg/collect/cluster_info.go
  pkg/collect/cluster_resources.go
  pkg/collect/collectd.go
  pkg/collect/collector.go
  pkg/collect/collector_test.go
  pkg/collect/configmap.go
  pkg/collect/configmap_test.go
  pkg/collect/copy.go
  pkg/collect/copy_from_host.go
  pkg/collect/data.go
  pkg/collect/exec.go
  pkg/collect/host_http.go
  pkg/collect/http.go
  pkg/collect/logs.go
  pkg/collect/longhorn.go
  pkg/collect/mysql.go
  pkg/collect/postgres.go
  pkg/collect/rbac.go
  pkg/collect/redis.go
  pkg/collect/registry.go
  pkg/collect/run.go
  pkg/collect/run_pod.go
  pkg/collect/secret.go
  pkg/collect/secret_test.go
  pkg/collect/sysctl.go
  pkg/preflight/collect.go
  pkg/supportbundle/collect.go
Labels: type::feature

#729 Collect resourcequotas
  pkg/collect/cluster_resources.go
Labels: type::feature

#757 Update golang.org/x/net to current version
  go.mod
  go.sum
Labels: bug::normal, type::security

#702 `uri:` implementation
  pkg/supportbundle/load.go
  pkg/supportbundle/supportbundle.go
  pkg/supportbundle/test/bad-upstream-uri-spec.yaml
  pkg/supportbundle/test/bad-uri-spec.yaml
  pkg/supportbundle/test/uri-spec.yaml
Labels: type::feature

#758 Wrap more information url in the analyser message
  .gitignore
  cmd/troubleshoot/cli/interactive_results.go
  examples/support-bundle/sample-supportbundle.yaml
Labels: type::bug

#761 E2E Tests for Support Bundle CLI
  .github/workflows/build-test-deploy.yaml
  Makefile
  examples/support-bundle/e2e.yaml
  test/validate-support-bundle-e2e.sh
Labels: type::chore

#727 minor lint update for README.md
  README.md
Labels: type::chore

#717 Issue #695 - Add `--no-uri` flag to `support-bundle` to ignore the uri field and revert back to the default spec…
  cmd/troubleshoot/cli/root.go
  cmd/troubleshoot/cli/run.go
Labels: type::feature

#752 Add golangci-lint linter make target
  .golangci.yaml
  CONTRIBUTING.md
  Makefile
Labels: type::chore

#769 make runPreflight and preflight cli flags public
  cmd/preflight/cli/root.go
  pkg/preflight/flags.go
  pkg/preflight/interactive_results.go
  pkg/preflight/run.go
  pkg/preflight/stdout_results.go
  pkg/preflight/upload_results.go
Labels: type::chore

#771 Make all Collector Fields Public
  pkg/collect/ceph.go
  pkg/collect/collectd.go
  pkg/collect/configmap.go
  pkg/collect/copy.go
  pkg/collect/copy_from_host.go
  pkg/collect/data.go
  pkg/collect/exec.go
  pkg/collect/logs.go
  pkg/collect/longhorn.go
  pkg/collect/mysql.go
  pkg/collect/postgres.go
  pkg/collect/redis.go
  pkg/collect/registry.go
  pkg/collect/run.go
  pkg/collect/run_pod.go
  pkg/collect/secret.go
  pkg/collect/sysctl.go
Labels: type::bug, bug::normal

#772 Update github.com/sylabs/sif/v2 to 2.8.1
  go.mod
  go.sum
Labels: type::security

#773 bump golang.org/x/text to 0.3.8
  go.mod
  go.sum
Labels: type::security

#766 Supports the Kubernetes distribution analyzer identifying VMware Tanzu
  pkg/analyze/distribution.go
Labels: type::feature

#776 Fix Preflight CheckRBAC
  pkg/preflight/collect.go
  preflight_default.yaml
Labels: type::bug, bug::regression

#781 Fix Progress Callback for Support Bundle Collection
  pkg/collect/cluster_info.go
  pkg/collect/cluster_resources.go
  pkg/collect/collectd.go
  pkg/collect/collector.go
  pkg/collect/configmap.go
  pkg/collect/copy.go
  pkg/collect/copy_from_host.go
  pkg/collect/data.go
  pkg/collect/exec.go
  pkg/collect/http.go
  pkg/collect/logs.go
  pkg/collect/longhorn.go
  pkg/collect/mysql.go
  pkg/collect/postgres.go
  pkg/collect/redis.go
  pkg/collect/registry.go
  pkg/collect/run.go
  pkg/collect/run_pod.go
  pkg/collect/secret.go
  pkg/collect/sysctl.go
  pkg/supportbundle/collect.go
Labels: type::bug, bug::regression

#779 Add collection of roles, cluster roles and their bindings
  pkg/collect/cluster_resources.go
Labels: type::feature

#790 plug `sbctl`
  README.md
Labels: type::feature, type::docs

#782 Remove unused Preflight spec
  collect_local.yaml
  collect_remote.yaml
  preflight_default.yaml
  preflight_local.yaml
  preflight_remote.yaml
Labels: type::chore

#796 Fix Host Certificate Analyzer
  pkg/analyze/host_certificate.go
Labels: type::bug, bug::normal

#799 Fix Ceph Title
  pkg/collect/ceph.go
Labels: type::bug, bug::regression

#803 Update FOSSA API key
  .github/workflows/pr-license-scan.yaml
Labels: type::chore

#804 Update cluster_resources.go
  pkg/collect/cluster_resources.go
Labels: type::bug

#768 Ensure clusterResources is added prior to other collectors
  cmd/troubleshoot/cli/root.go
  pkg/collect/collect.go
  pkg/collect/collect_test.go
  pkg/preflight/collect.go
  pkg/supportbundle/collect.go
Labels: type::bug, bug::normal
