Repository replicatedhq/troubleshoot, pull requests merged in 2022-02, with the labels that each got.

#534 include atomic collector statuses
  pkg/preflight/collect.go
Labels: type::feature

#538 improvement: added --output flag for preflight and support bundle
  cmd/preflight/cli/interactive_results.go
  cmd/preflight/cli/root.go
  cmd/preflight/cli/run.go
  cmd/troubleshoot/cli/root.go
  cmd/troubleshoot/cli/run.go
  pkg/convert/output.go
  pkg/supportbundle/supportbundle.go
Labels: type::feature, team::orange

#539 Add `strict` flag to Analyzers and ResultAnalyzers
  cmd/preflight/cli/interactive_results.go
  cmd/preflight/cli/stdout_results.go
  cmd/preflight/cli/upload_results.go
  config/crds/troubleshoot.sh_analyzers.yaml
  config/crds/troubleshoot.sh_hostcollectors.yaml
  config/crds/troubleshoot.sh_hostpreflights.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/fake/clientset_generated.go
  github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/fake/register.go
  pkg/analyze/analyzer.go
  pkg/apis/troubleshoot/v1beta2/analyzer_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  pkg/preflight/types.go
  schemas/analyzer-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::feature, team::blue

#542 Fix `strict` flag mapping
  pkg/analyze/analyzer.go
  pkg/multitype/boolstring.go
  pkg/multitype/boolstring_test.go
Labels: type::bug, bug::normal, team::blue
