Repository replicatedhq/troubleshoot, pull requests merged in 2022-08, with the labels that each got.

#661 Require PR labels
  .github/workflows/require-pr-labels.yaml
Labels: type::chore

#662 Add design proposal for mergeable specs
  design/proposal-mergeable-spec.md
Labels: type::docs

#644 Allow custom messages to be passed if a deployment/statefulset is absent
  pkg/analyze/common_status.go
  pkg/analyze/deployment_status.go
  pkg/analyze/deployment_status_test.go
  pkg/analyze/statefulset_status.go
  pkg/analyze/statefulset_status_test.go
Labels: type::feature

#679 update GHA runner from 18.04 [sc-56448]
  .github/workflows/build-test-deploy.yaml
Labels: type::chore

#594 Check if user has access to namespace resources before collecting
  config/crds/troubleshoot.sh_collectors.yaml
  config/crds/troubleshoot.sh_hostcollectors.yaml
  config/crds/troubleshoot.sh_hostpreflights.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  pkg/apis/troubleshoot/v1beta2/collector_shared.go
  pkg/collect/cluster_resources.go
  schemas/collector-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::bug, bug::normal, team::orange

#686 Add Design Principles to the design folder
  CONTRIBUTING.md
  design/design-principles.md
Labels: type::docs

#693 Update to go 1.19
  .github/workflows/build-test-deploy.yaml
  go.mod
  go.sum
Labels: type::chore

#681 add proposal for updateable specs
  design/proposal-updateable-specs.md
Labels: type::feature
