Repository replicatedhq/troubleshoot, pull requests merged in 2023-05, with the labels that each got.

#1135 support multiple exit codes based on what went wrong/right
  .github/workflows/build-test-deploy.yaml
  cmd/preflight/cli/root.go
  pkg/constants/constants.go
  pkg/preflight/run.go
  pkg/preflight/run_test.go
  pkg/types/types.go
Labels: type::feature

#1153 Search stdin for secrets with preflight specs
  pkg/preflight/read_specs.go
  pkg/preflight/read_specs_test.go
  pkg/preflight/run.go
  testdata/preflightspec/troubleshoot_v1beta2_preflight_secret_gotest.yaml
  testdata/preflightspec/troubleshoot_v1beta2_preflight_secret_stringdata_gotest.yaml
Labels: type::feature

#1155 fix: logs collector timeout prevent concurrent map iteration and map write
  pkg/collect/logs.go
Labels: type::bug, bug::regression

#1159 feat(collector): add priority class resources
  pkg/collect/cluster_resources.go
  pkg/constants/constants.go
Labels: type::feature

#1165 fix(collector): cluster resource file names
  pkg/collect/cluster_resources.go
  pkg/constants/constants.go
Labels: type::bug, bug::regression

#1181 fix (support-bundle): Ensure specs are merged correctly
  cmd/troubleshoot/cli/run.go
  pkg/specs/configmaps.go
  pkg/specs/secrets.go
  test/validate-support-bundle-e2e.sh
  testdata/supportbundle/labelled-specs/0-ns.yaml
  testdata/supportbundle/labelled-specs/redact-spec-1.yaml
  testdata/supportbundle/labelled-specs/redact-spec-2.yaml
  testdata/supportbundle/labelled-specs/sb-spec-1.yaml
  testdata/supportbundle/labelled-specs/sb-spec-2.yaml
Labels: type::bug, bug::regression

#1172 Capture `runPod` status and events before deleting the pod
  pkg/collect/run_pod.go
Labels: type::feature

#1128 feat(analyzer): add certificate analyzer
  config/crds/troubleshoot.sh_analyzers.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  pkg/analyze/analyzer.go
  pkg/analyze/certificates.go
  pkg/analyze/certificates_test.go
  pkg/apis/troubleshoot/v1beta2/analyzer_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  pkg/collect/certificates.go
  schemas/analyzer-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::feature

#1185 feat(analyzer): fix clusterResource analyzer always uses the first object found
  pkg/analyze/kube_resource.go
  pkg/analyze/kube_resource_test.go
Labels: type::bug, bug::normal

#1189 Add regex to `clusterResources` analyzer
  config/crds/troubleshoot.sh_analyzers.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  pkg/analyze/files/support-bundle/cluster-resources/pvcs/default.json
  pkg/analyze/kube_resource.go
  pkg/analyze/kube_resource_test.go
  pkg/apis/troubleshoot/v1beta2/analyzer_shared.go
  schemas/analyzer-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::feature

#1197 chore: update deprecated trivy cli option
  Makefile
Labels: type::chore
