Repository replicatedhq/troubleshoot, pull requests merged in 2023-01, with the labels that each got.

#941 Improve build-test-deploy GitHub Actions performance
  .github/workflows/build-test-deploy.yaml
  deploy/.goreleaser.yaml
Labels: type::chore

#939 preflight: fix segfault when collector's are not defined in YAML
  pkg/preflight/collect.go
  pkg/preflight/run.go
Labels: type::bug, bug::normal

#887 feat(redactors): Run redactors on an existing support bundle
  .gitignore
  Makefile
  README.md
  cmd/collect/cli/run.go
  cmd/troubleshoot/cli/redact.go
  cmd/troubleshoot/cli/root.go
  cmd/troubleshoot/cli/run.go
  cmd/troubleshoot/cli/version.go
  docs/preflight.md
  docs/preflight_version.md
  docs/support-bundle.md
  docs/support-bundle_analyze.md
  docs/support-bundle_redact.md
  docs/support-bundle_version.md
  examples/redact/e2e.yaml
  internal/testutils/utils.go
  pkg/analyze/download.go
  pkg/analyze/download_test.go
  pkg/collect/postgres_test.go
  pkg/collect/redact.go
  pkg/collect/redis_test.go
  pkg/collect/result.go
  pkg/collect/result_test.go
  pkg/collect/util_test.go
  pkg/constants/constants.go
  pkg/supportbundle/collect.go
  pkg/supportbundle/load.go
  pkg/supportbundle/supportbundle.go
  test/validate-support-bundle-e2e.sh
  testdata/supportbundle/extracted-sb/cluster-resources/pods/logs/default/static-hi/static-hi.log
  testdata/supportbundle/extracted-sb/static-hi.log
  testdata/supportbundle/missing-version.tar.gz
  testdata/supportbundle/support-bundle.tar.gz
Labels: type::feature

#942 GitHub Action goreleaser-test - convert to a matrix
  .github/workflows/build-test-deploy.yaml
  deploy/.goreleaser.yaml
Labels: type::chore

#940 preflight: add yaml output format
  pkg/preflight/stdout_results.go
Labels: type::bug, bug::normal

#926 chore: Add CLI flags to enable CPU & memory profiling
  CONTRIBUTING.md
  cmd/analyze/cli/root.go
  cmd/collect/cli/root.go
  cmd/preflight/cli/root.go
  cmd/troubleshoot/cli/analyze.go
  cmd/troubleshoot/cli/root.go
  cmd/util/profilers.go
  docs/preflight.md
  docs/preflight_version.md
  docs/support-bundle.md
  docs/support-bundle_analyze.md
  docs/support-bundle_redact.md
  docs/support-bundle_version.md
Labels: type::chore

#925 Implementation of maximum pod logsize - Fixes issue 878
  config/crds/troubleshoot.sh_collectors.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  examples/support-bundle/sample-supportbundle.yaml
  pkg/apis/troubleshoot/v1beta2/collector_shared.go
  pkg/collect/cluster_resources.go
  pkg/collect/logs.go
  pkg/collect/logs_test.go
  pkg/collect/run_pod.go
  schemas/collector-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::feature

#946 Added note in to clarify purpose of `MaxBytes` in cluster_resources.go
  pkg/collect/cluster_resources.go
Labels: type::feature

#952 fix: Collect logs from all pods specified in logs collector spec
  pkg/collect/logs.go
  pkg/collect/logs_test.go
  pkg/constants/constants.go
Labels: type::bug, bug::regression

#948 CVE: bump golang.org/x/net
  go.mod
  go.sum
Labels: type::security

#943 feat(support-bundle): silent result if ceph or longhorn addon not enabled
  cmd/troubleshoot/cli/root.go
  pkg/analyze/analyzer.go
  pkg/analyze/ceph.go
  pkg/analyze/ceph_test.go
  pkg/analyze/download.go
  pkg/collect/ceph.go
  pkg/collect/longhorn.go
  pkg/types/types.go
Labels: type::bug, bug::normal

#953 chore: Use org secret for username
  .github/workflows/build-test-deploy.yaml
Labels: type::chore

#951 preflight: ensure --output produces an output file of the desired format
  pkg/preflight/interactive_results.go
  pkg/preflight/output_to_file.go
  pkg/preflight/run.go
  pkg/preflight/stdout_results.go
  pkg/preflight/text_results.go
Labels: type::bug, bug::normal

#949 adding test coverage for preflight.RunPreflights()
  .github/workflows/build-test-deploy.yaml
  Makefile
  internal/testutils/utils.go
  pkg/preflight/run_test.go
  testdata/preflightspec/troubleshoot_v1beta2_preflight_gotest.yaml
Labels: type::chore

#959 Upgrade dependencies
  go.mod
  go.sum
  pkg/analyze/cluster_version.go
  pkg/analyze/cluster_version_test.go
  pkg/analyze/database_shared.go
  pkg/analyze/host_os_info.go
  pkg/collect/host_time.go
  pkg/collect/registry.go
Labels: type::chore

#975 CONTRIBUTING.md - fix path for design principles doc
  CONTRIBUTING.md
Labels: type::bug, bug::normal, type::docs

#981 feat(hostpreflights): udp port status
  config/crds/troubleshoot.sh_analyzers.yaml
  config/crds/troubleshoot.sh_hostcollectors.yaml
  config/crds/troubleshoot.sh_hostpreflights.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_remotecollectors.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  examples/collect/host/udp-port.yaml
  examples/collect/remote/udp-port.yaml
  examples/preflight/host/udp-port.yaml
  examples/preflight/remote/udp-port.yaml
  pkg/analyze/host_analyzer.go
  pkg/analyze/host_udpportstatus.go
  pkg/analyze/host_udpportstatus_test.go
  pkg/apis/troubleshoot/v1beta2/hostanalyzer_shared.go
  pkg/apis/troubleshoot/v1beta2/hostcollector_shared.go
  pkg/apis/troubleshoot/v1beta2/remote_collector_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  pkg/client/troubleshootclientset/clientset.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_analyzer.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_collector.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_preflight.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_redactor.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_supportbundle.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/troubleshoot_client.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_analyzer.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_collector.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_hostcollector.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_hostpreflight.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_preflight.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_redactor.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_remotecollector.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_supportbundle.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/troubleshoot_client.go
  pkg/collect/host_collector.go
  pkg/collect/host_udpportstatus.go
  pkg/collect/host_udpportstatus_test.go
  pkg/collect/remote_collector.go
  schemas/analyzer-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::feature

#971 Standardize Cluster Resources Collector File Paths
  pkg/analyze/cluster_pod_statuses.go
  pkg/analyze/container_runtime.go
  pkg/analyze/crd.go
  pkg/analyze/deployment_status.go
  pkg/analyze/distribution.go
  pkg/analyze/image_pull_secret.go
  pkg/analyze/ingress.go
  pkg/analyze/job_status.go
  pkg/analyze/kube_resource.go
  pkg/analyze/node_resources.go
  pkg/analyze/replicaset_status.go
  pkg/analyze/statefulset_status.go
  pkg/analyze/storage_class.go
  pkg/collect/cluster_resources.go
  pkg/collect/logs.go
  pkg/constants/constants.go
  pkg/redact/redact.go
  pkg/supportbundle/parse.go
Labels: type::chore

#983 chore: Filter tests to run when calling make test
  CONTRIBUTING.md
  Makefile
Labels: type::chore

#986 Fixes issue 985. update readme to change the flags on the cosign command
  README.md
Labels: type::bug, bug::normal, type::docs
