Repository replicatedhq/troubleshoot, pull requests merged in 2023-03, with the labels that each got.

#1045 feat: support for rhel 9 variants (rhel, centos, ol, rocky)
  config/crds/troubleshoot.sh_hostcollectors.yaml
  config/crds/troubleshoot.sh_hostpreflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  examples/preflight/host/system-packages.yaml
  pkg/apis/troubleshoot/v1beta2/hostcollector_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  pkg/client/troubleshootclientset/clientset.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_analyzer.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_collector.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_preflight.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_redactor.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_supportbundle.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/troubleshoot_client.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_analyzer.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_collector.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_hostcollector.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_hostpreflight.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_preflight.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_redactor.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_remotecollector.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_supportbundle.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/troubleshoot_client.go
  pkg/collect/host_block_device.go
  pkg/collect/host_block_device_test.go
  pkg/collect/host_system_package.go
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::feature

#1042 fix: Use namespace from the collector spec for Ceph
  pkg/collect/ceph.go
Labels: type::bug, bug::regression

#1004 Collector/Analyzer - Subnet Available
  config/crds/troubleshoot.sh_analyzers.yaml
  config/crds/troubleshoot.sh_hostcollectors.yaml
  config/crds/troubleshoot.sh_hostpreflights.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_remotecollectors.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  examples/preflight/host/subnet-available.yaml
  go.mod
  go.sum
  pkg/analyze/host_analyzer.go
  pkg/analyze/host_subnetavailable.go
  pkg/apis/troubleshoot/v1beta2/hostanalyzer_shared.go
  pkg/apis/troubleshoot/v1beta2/hostcollector_shared.go
  pkg/apis/troubleshoot/v1beta2/remote_collector_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  pkg/collect/host_collector.go
  pkg/collect/host_subnetavailable.go
  pkg/collect/host_subnetavailable_test.go
  pkg/collect/remote_collector.go
  schemas/analyzer-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::feature

#966 dont run tests on draft PRs
  .github/workflows/build-test-deploy.yaml
Labels: type::chore, type::tests

#1056 feat(analyzer): remove duplicated analyzers
  pkg/analyze/analyzer.go
  pkg/analyze/analyzer_test.go
  pkg/supportbundle/supportbundle.go
Labels: type::bug, bug::normal

#1065 fix: Fix longhorn collector linting error
  pkg/collect/longhorn.go
Labels: type::chore

#1074 feat: Build and release binaries for Linux ARM 32-bit
  .github/workflows/build-test-deploy.yaml
  deploy/.goreleaser.yaml
  deploy/krew/preflight.yaml
  deploy/krew/support-bundle.yaml
Labels: type::chore

#1077 chore: Add community calendar to README
  README.md
Labels: type::chore, type::docs

#1063 feat: Add partition type info to block device collector
  pkg/analyze/host_block_devices.go
  pkg/analyze/host_block_devices_test.go
  pkg/collect/host_block_device.go
Labels: type::feature

#1091 fix:Revert namespace filename for cluster-resources back to namespaces.json
  pkg/constants/constants.go
Labels: type::bug, bug::regression
