Repository replicatedhq/troubleshoot, pull requests merged in 2023-09, with the labels that each got.

#1310 add http collector timeouts; fixes #1064
  config/crds/troubleshoot.replicated.com_collectors.yaml
  config/crds/troubleshoot.replicated.com_preflights.yaml
  config/crds/troubleshoot.replicated.com_supportbundles.yaml
  config/crds/troubleshoot.sh_collectors.yaml
  config/crds/troubleshoot.sh_hostcollectors.yaml
  config/crds/troubleshoot.sh_hostpreflights.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_remotecollectors.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  pkg/apis/troubleshoot/v1beta1/collector_shared.go
  pkg/apis/troubleshoot/v1beta2/collector_shared.go
  pkg/collect/host_http.go
  pkg/collect/http.go
  pkg/collect/http_test.go
  schemas/collector-troubleshoot-v1beta1.json
  schemas/collector-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta1.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta1.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::feature

#1321 chore: update Go to 1.20
  .github/workflows/build-test-deploy.yaml
  go.mod
Labels: type::chore

#1322 chore: Update Go version in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: type::chore

#1323 chore: update k8s.io to v0.28.1
  config/crds/troubleshoot.sh_collectors.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  go.mod
  go.sum
  schemas/collector-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::chore

#1240 feat: Dry run flag to print preflight specs to std out
  cmd/analyze/cli/root.go
  cmd/collect/cli/root.go
  cmd/collect/cli/version.go
  cmd/internal/util/profilers.go
  cmd/internal/util/version.go
  cmd/preflight/cli/root.go
  cmd/preflight/cli/version.go
  cmd/troubleshoot/cli/root.go
  docs/preflight.md
  docs/preflight_oci-fetch.md
  docs/preflight_version.md
  docs/support-bundle.md
  docs/support-bundle_analyze.md
  docs/support-bundle_redact.md
  docs/support-bundle_version.md
  go.mod
  internal/testutils/utils.go
  pkg/loader/loader.go
  pkg/loader/loader_test.go
  pkg/preflight/flags.go
  pkg/preflight/read_specs.go
  pkg/preflight/read_specs_test.go
  pkg/preflight/run.go
  pkg/preflight/validate_specs.go
  pkg/preflight/validate_specs_test.go
Labels: type::feature

#1333 Fix incorrect result URI for pass and warn outcomes in common status analyzer
  examples/preflight/host/cpu.yaml
  pkg/analyze/common_status.go
Labels: type::bug, bug::regression
