Repository replicatedhq/troubleshoot, pull requests merged in 2023-02, with the labels that each got.

#998 fix: address runtime error of nil pointer about concatenating preflig…
  pkg/preflight/concat.go
  pkg/preflight/run.go
Labels: type::bug, bug::normal

#997 chore: chore: update binaries used to build manifests and k8s
  Makefile
  config/crds/troubleshoot.replicated.com_analyzers.yaml
  config/crds/troubleshoot.replicated.com_collectors.yaml
  config/crds/troubleshoot.replicated.com_preflights.yaml
  config/crds/troubleshoot.replicated.com_redactors.yaml
  config/crds/troubleshoot.replicated.com_supportbundles.yaml
  config/crds/troubleshoot.sh_analyzers.yaml
  config/crds/troubleshoot.sh_collectors.yaml
  config/crds/troubleshoot.sh_hostcollectors.yaml
  config/crds/troubleshoot.sh_hostpreflights.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_redactors.yaml
  config/crds/troubleshoot.sh_remotecollectors.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  pkg/client/troubleshootclientset/clientset.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_analyzer.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_collector.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_preflight.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_redactor.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_supportbundle.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/troubleshoot_client.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_analyzer.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_collector.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_hostcollector.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_hostpreflight.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_preflight.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_redactor.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_remotecollector.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_supportbundle.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/troubleshoot_client.go
  schemas/collector-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::chore, dependencies

#972 Deduplication for In-Cluster Collectors
  cmd/troubleshoot/cli/run.go
  pkg/collect/collect.go
  pkg/collect/collector.go
  pkg/collect/collector_test.go
  pkg/preflight/collect.go
  pkg/supportbundle/collect.go
Labels: type::feature

#1002 refactor: keep support bundle concat logic to be consistent with Preflight concat
  cmd/troubleshoot/cli/run.go
  pkg/supportbundle/supportbundle.go
  pkg/supportbundle/supportbundle_test.go
Labels: type::chore

#935 feat: Record summary of execution times of support bundle operations (collect/redact/analyse)
  Makefile
  cmd/preflight/cli/root.go
  cmd/troubleshoot/cli/root.go
  cmd/troubleshoot/cli/version.go
  examples/support-bundle/sample-supportbundle.yaml
  go.mod
  go.sum
  internal/traces/exporter.go
  internal/traces/exporter_test.go
  internal/traces/otel.go
  pkg/analyze/analyzer.go
  pkg/analyze/analyzer_test.go
  pkg/analyze/download.go
  pkg/collect/host_udpportstatus_test.go
  pkg/constants/constants.go
  pkg/preflight/analyze.go
  pkg/preflight/collect.go
  pkg/preflight/run.go
  pkg/supportbundle/collect.go
  pkg/supportbundle/supportbundle.go
Labels: type::feature

#1011 chore: Don't hardcode /bin/bash
  Makefile
  scripts/host-preflight-integration-test.sh
  scripts/initialize-sbom-build.sh
  test/validate-preflight-e2e.sh
  test/validate-support-bundle-e2e.sh
Labels: type::chore

#1012 chore: Don't print which error in Makefile
  Makefile
Labels: type::chore

#1013 chore: remove unused code
  cmd/troubleshoot/cli/run.go
  cmd/troubleshoot/cli/util.go
  cmd/troubleshoot/cli/version.go
  pkg/collect/collector.go
  pkg/collect/configmap_test.go
  pkg/collect/copy.go
  pkg/collect/secret_test.go
  pkg/debug/log.go
  pkg/oci/creds.go
  pkg/specs/configmaps_test.go
  pkg/specs/secrets_test.go
Labels: type::chore

#1015 remove PR label enforcement workflow
  .github/workflows/require-pr-labels.yaml
Labels: type::chore

#1010 feat(support-bundle): print progress in debug non-interactive mode
  cmd/troubleshoot/cli/run.go
Labels: type::feature

#1008 feat: use klog as the default logging library
  Makefile
  cmd/analyze/cli/root.go
  cmd/collect/cli/root.go
  cmd/preflight/cli/root.go
  cmd/troubleshoot/cli/analyze.go
  cmd/troubleshoot/cli/redact.go
  cmd/troubleshoot/cli/root.go
  cmd/troubleshoot/cli/run.go
  cmd/util/util.go
  internal/traces/otel.go
  pkg/analyze/analyzer.go
  pkg/analyze/download.go
  pkg/collect/ceph.go
  pkg/collect/collect.go
  pkg/collect/copy_from_host.go
  pkg/collect/logs.go
  pkg/collect/longhorn.go
  pkg/collect/redact.go
  pkg/collect/run_pod.go
  pkg/collect/runner.go
  pkg/collect/sysctl.go
  pkg/logger/logger.go
  pkg/preflight/analyze.go
  pkg/preflight/collect.go
  pkg/redact/yaml.go
  pkg/supportbundle/collect.go
  pkg/supportbundle/load.go
  pkg/supportbundle/supportbundle.go
Labels: type::feature
