Repository replicatedhq/troubleshoot, pull requests merged in 2023-12, with the labels that each got.

#1396 fix(support-bundle): add Replicated user-agent header to the correct URLs
  internal/specs/specs.go
  internal/specs/specs_test.go
Labels: type::bug, bug::normal

#1398 feat: goldpinger collector and analyser
  config/crds/troubleshoot.sh_analyzers.yaml
  config/crds/troubleshoot.sh_collectors.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  internal/testutils/utils.go
  internal/util/util.go
  pkg/analyze/analyzer.go
  pkg/analyze/goldpinger.go
  pkg/analyze/goldpinger_test.go
  pkg/apis/troubleshoot/v1beta2/analyzer_shared.go
  pkg/apis/troubleshoot/v1beta2/collector_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  pkg/collect/collector.go
  pkg/collect/exec.go
  pkg/collect/goldpinger.go
  pkg/collect/run.go
  pkg/collect/run_pod.go
  pkg/collect/runner.go
  pkg/collect/util.go
  pkg/collect/util_test.go
  pkg/constants/constants.go
  schemas/analyzer-troubleshoot-v1beta2.json
  schemas/collector-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
  test/e2e/support-bundle/cluster_pod_statuses_e2e_test.go
  test/e2e/support-bundle/cluster_resources_e2e_test.go
  test/e2e/support-bundle/goldpinger_collector_e2e_test.go
  test/e2e/support-bundle/helm_collector_e2e_test.go
  test/e2e/support-bundle/main_e2e_test.go
  testdata/charts/goldpinger-6.0.1.tgz
  testdata/goldpinger/checkall-success.json
  testdata/goldpinger/checkall-with-error.json
Labels: type::feature

#1400 fix: flaky e2e test
  pkg/collect/goldpinger.go
  pkg/collect/run_pod.go
  test/e2e/support-bundle/goldpinger_collector_e2e_test.go
Labels: type::chore

#1397 chore(preflight): Better error message when not results found
  pkg/preflight/run.go
Labels: type::chore

#1409 bump github actions/download-artifact
  .github/workflows/build-test-deploy.yaml
  .github/workflows/license.yaml
Labels: type::chore

#1411 Update containers/image, oras-go, and docker
  examples/sdk/helm-template/go.mod
  examples/sdk/helm-template/go.sum
  go.mod
  go.sum
  pkg/client/troubleshootclientset/clientset.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_analyzer.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_collector.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_preflight.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_redactor.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_supportbundle.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/troubleshoot_client.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_analyzer.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_collector.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_hostcollector.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_hostpreflight.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_preflight.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_redactor.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_remotecollector.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_supportbundle.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/troubleshoot_client.go
Labels: type::chore, go
