Repository replicatedhq/troubleshoot, pull requests merged in 2023-04, with the labels that each got.

#1098 fix: Discover specs from namespaces user is allowed
  cmd/troubleshoot/cli/run.go
  pkg/k8sutil/auth.go
  pkg/k8sutil/namespace.go
Labels: type::bug, bug::regression

#1072 feat(krew): add linux/arm64 to krew plugin manifests
  deploy/krew/preflight.yaml
  deploy/krew/support-bundle.yaml
Labels: type::chore

#1101 fix: Correct arm release file names in krew config
  deploy/krew/preflight.yaml
  deploy/krew/support-bundle.yaml
Labels: type::bug, bug::regression

#1068 feat(collector): Add host collector to copy files to a bundle
  Makefile
  config/crds/troubleshoot.sh_hostcollectors.yaml
  config/crds/troubleshoot.sh_hostpreflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  internal/testutils/utils.go
  pkg/apis/troubleshoot/v1beta2/collector_shared.go
  pkg/apis/troubleshoot/v1beta2/hostcollector_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  pkg/collect/host_collector.go
  pkg/collect/host_copy.go
  pkg/collect/host_copy_test.go
  pkg/collect/result.go
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::feature

#1088 fix/clusterPodStatuses: only process `when` conditional if specified
  pkg/analyze/cluster_pod_statuses.go
  pkg/analyze/cluster_pod_statuses_test.go
  pkg/analyze/data_test.go
  pkg/analyze/files/pods/default-unhealthy.json
  pkg/analyze/files/pods/default.json
  pkg/analyze/files/pods/other-unhealthy.json
  pkg/analyze/files/pods/other.json
  pkg/client/troubleshootclientset/clientset.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_analyzer.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_collector.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_preflight.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_redactor.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/fake/fake_supportbundle.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta1/troubleshoot_client.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_analyzer.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_collector.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_hostcollector.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_hostpreflight.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_preflight.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_redactor.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_remotecollector.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_supportbundle.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/troubleshoot_client.go
Labels: type::bug, bug::normal

#1113 feat(action): add git fetch all history for all branches and tags in tests
  .github/workflows/build-test-deploy.yaml
Labels: type::bug, bug::normal

#1115 fix: HostPreflight tcpConnect analyzer should use first matching outcome
  pkg/analyze/host_tcp_connect.go
  pkg/analyze/host_tcp_connect_test.go
Labels: type::bug, bug::normal

#1118 FOSSA process refinements
  .github/workflows/fossa.yaml
  .github/workflows/pr-license-scan.yaml
Labels: type::chore

#1114 Add stdin and multidoc support to preflight.
  pkg/preflight/run.go
  test/validate-preflight-e2e.sh
Labels: type::feature

#1117 Add ability to fetch preflights from OCI registry to standard out
  cmd/preflight/cli/oci_fetch.go
  cmd/preflight/cli/root.go
Labels: type::feature

#1116 bump: update kubernetes dependencies to v0.27.0
  config/crds/troubleshoot.sh_collectors.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  go.mod
  go.sum
  schemas/collector-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::chore

#1121 Revert "feat: Add partition type info to block device collector"
  pkg/analyze/host_block_devices.go
  pkg/analyze/host_block_devices_test.go
  pkg/collect/host_block_device.go
Labels: type::bug, bug::regression

#1119 feat(certificate): support array of certificates from configmaps and secrets
  config/crds/troubleshoot.sh_collectors.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  pkg/apis/troubleshoot/v1beta2/collector_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  pkg/collect/certificates.go
  pkg/collect/certificates_test.go
  schemas/collector-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::feature
