Repository replicatedhq/troubleshoot, pull requests merged in 2023-10, with the labels that each got.

#1275 call out to `fio` for host filesystem performance
  go.mod
  go.sum
  pkg/analyze/host_filesystem_performance.go
  pkg/analyze/host_filesystem_performance_test.go
  pkg/collect/host_filesystem_performance.go
  pkg/collect/host_filesystem_performance_linux.go
  pkg/collect/host_filesystem_performance_test.go
  testdata/filesystem_performance_preflight.yaml
  testdata/kurl_preflights.yaml
Labels: type::feature, echoes/effort: M

#1358 feat: add ceph df to ceph collector
  pkg/collect/ceph.go
Labels: type::feature

#1359 Fix mssql and mysql analyzers
  pkg/analyze/mssql.go
  pkg/analyze/mysql.go
Labels: type::bug, bug::regression

#1371 fix: embed troubleshoot version string from module dependency
  cmd/analyze/cli/run.go
  pkg/version/version.go
Labels: bug::normal

#1375 fix: Correct how configmap and secrets paths are parsed in the CLI
  internal/specs/specs.go
  test/validate-support-bundle-e2e.sh
  testdata/supportbundle/labelled-specs/redact-spec-1.yaml
  testdata/supportbundle/labelled-specs/redact-spec-2.yaml
  testdata/supportbundle/labelled-specs/redact-spec-3.yaml
  testdata/supportbundle/labelled-specs/redact-spec-4.yaml
  testdata/supportbundle/labelled-specs/sb-spec-1.yaml
  testdata/supportbundle/labelled-specs/sb-spec-2.yaml
  testdata/supportbundle/labelled-specs/sb-spec-3.yaml
  testdata/supportbundle/labelled-specs/sb-spec-4.yaml
Labels: type::bug, bug::regression

#1383 Gracefully handle unreachable URIs in loadSupportBundleSpecsFromURIs
  cmd/troubleshoot/cli/run.go
  cmd/troubleshoot/cli/run_test.go
Labels: type::bug, bug::regression
