Repository replicatedhq/troubleshoot, pull requests merged in 2023-07, with the labels that each got.

#1250 feat(preflight): add detail warning message when validating preflight and host preflight spec
  pkg/preflight/run.go
  pkg/preflight/validate_specs.go
  pkg/preflight/validate_specs_test.go
  pkg/types/types.go
  testdata/preflightspec/troubleshoot_v1beta2_host_preflight_validate_empty_analyzers_gotest.yaml
  testdata/preflightspec/troubleshoot_v1beta2_host_preflight_validate_empty_collectors_gotest.yaml
  testdata/preflightspec/troubleshoot_v1beta2_host_preflight_validate_excluded_analyzers_gotest.yaml
  testdata/preflightspec/troubleshoot_v1beta2_host_preflight_validate_excluded_collectors_gotest.yaml
  testdata/preflightspec/troubleshoot_v1beta2_preflight_validate_empty_analyzers_gotest.yaml
  testdata/preflightspec/troubleshoot_v1beta2_preflight_validate_empty_collectors_gotest.yaml
  testdata/preflightspec/troubleshoot_v1beta2_preflight_validate_excluded_all_default_collectors_gotest.yaml
  testdata/preflightspec/troubleshoot_v1beta2_preflight_validate_excluded_all_non_default_collectors_gotest.yaml
  testdata/preflightspec/troubleshoot_v1beta2_preflight_validate_excluded_analyzers_gotest.yaml
  testdata/preflightspec/troubleshoot_v1beta2_preflight_validate_excluded_one_default_collectors_gotest.yaml
Labels: type::feature

#1262 fix(collector): cluster-resources PV filename pattern
  pkg/collect/cluster_resources.go
Labels: type::bug, bug::normal

#1261 feat(analyzer): add detailed message for unhealthy pod
  pkg/analyze/cluster_pod_statuses.go
  pkg/analyze/cluster_pod_statuses_test.go
  pkg/analyze/data_test.go
  pkg/analyze/files/events/message-container-creating-failed-mount.json
  pkg/analyze/files/events/message-image-pull-fail.json
  pkg/analyze/files/events/message-pod-init-crashloop-backoff.json
  pkg/analyze/files/pods/message-container-creating-failed-mount.json
  pkg/analyze/files/pods/message-image-pull-fail.json
  pkg/analyze/files/pods/message-oomkill-pod.json
  pkg/analyze/files/pods/message-pending-node-affinity.json
  pkg/analyze/files/pods/message-pending-pod-resources.json
  pkg/analyze/files/pods/message-pod-crashloop-backoff.json
  pkg/analyze/files/pods/message-pod-init-crashloop-backoff.json
  pkg/k8sutil/pod.go
Labels: type::feature

#1132 feat(host): add host certificate collector and analyzer
  config/crds/troubleshoot.sh_analyzers.yaml
  config/crds/troubleshoot.sh_hostcollectors.yaml
  config/crds/troubleshoot.sh_hostpreflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  pkg/analyze/host_analyzer.go
  pkg/analyze/host_certificates_collection.go
  pkg/analyze/host_certificates_collection_test.go
  pkg/apis/troubleshoot/v1beta2/hostanalyzer_shared.go
  pkg/apis/troubleshoot/v1beta2/hostcollector_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  pkg/collect/certificates.go
  pkg/collect/host_certificates_collection.go
  pkg/collect/host_certificates_collection_test.go
  pkg/collect/host_collector.go
  pkg/collect/util.go
  schemas/analyzer-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::feature

#1267 feat: Add regex host analyser
  Makefile
  config/crds/troubleshoot.sh_analyzers.yaml
  config/crds/troubleshoot.sh_hostcollectors.yaml
  config/crds/troubleshoot.sh_hostpreflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  pkg/analyze/analyzer.go
  pkg/analyze/host_analyzer.go
  pkg/analyze/host_block_devices.go
  pkg/analyze/host_block_devices_test.go
  pkg/analyze/host_certificate.go
  pkg/analyze/host_certificate_test.go
  pkg/analyze/host_certificates_collection.go
  pkg/analyze/host_certificates_collection_test.go
  pkg/analyze/host_cpu.go
  pkg/analyze/host_cpu_test.go
  pkg/analyze/host_disk_usage.go
  pkg/analyze/host_disk_usage_test.go
  pkg/analyze/host_filesystem_performance.go
  pkg/analyze/host_filesystem_performance_test.go
  pkg/analyze/host_http.go
  pkg/analyze/host_http_test.go
  pkg/analyze/host_httploadbalancer.go
  pkg/analyze/host_ipv4interfaces.go
  pkg/analyze/host_ipv4interfaces_test.go
  pkg/analyze/host_kernel_modules.go
  pkg/analyze/host_kernel_modules_test.go
  pkg/analyze/host_memory.go
  pkg/analyze/host_memory_test.go
  pkg/analyze/host_os_info.go
  pkg/analyze/host_os_info_test.go
  pkg/analyze/host_services.go
  pkg/analyze/host_services_test.go
  pkg/analyze/host_subnetavailable.go
  pkg/analyze/host_system_packages.go
  pkg/analyze/host_system_packages_test.go
  pkg/analyze/host_tcp_connect.go
  pkg/analyze/host_tcp_connect_test.go
  pkg/analyze/host_tcploadbalancer.go
  pkg/analyze/host_tcploadbalancer_test.go
  pkg/analyze/host_tcpportstatus.go
  pkg/analyze/host_tcpportstatus_test.go
  pkg/analyze/host_text_analyze.go
  pkg/analyze/host_time.go
  pkg/analyze/host_time_test.go
  pkg/analyze/host_udpportstatus.go
  pkg/analyze/host_udpportstatus_test.go
  pkg/analyze/text_analyze.go
  pkg/analyze/text_analyze_test.go
  pkg/apis/troubleshoot/v1beta2/hostanalyzer_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  schemas/analyzer-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::feature

#1271 fix: fixes #1270
  pkg/preflight/validate_specs.go
  pkg/preflight/validate_specs_test.go
  test/validate-preflight-e2e.sh
  testdata/preflightspec/troubleshoot_v1beta2_preflight_validate_spec_with_upload_results_gotest.yaml
Labels: type::bug, bug::regression

#1279 feat: Add Strict flag to LoadSpecs API
  internal/traces/exporter.go
  internal/traces/exporter_test.go
  pkg/loader/loader.go
  pkg/loader/loader_test.go
  testdata/yamldocs/multidoc-spec-with-invalids.yaml
Labels: type::feature

#1273 Fix(test): add unit tests for util
  internal/util/util_test.go
Labels: type::bug, bug::regression
