Repository replicatedhq/troubleshoot, pull requests merged in 2023-06, with the labels that each got.

#1200 fix(collector): removed unused name in certificates collector
  config/crds/troubleshoot.sh_collectors.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  pkg/apis/troubleshoot/v1beta2/collector_shared.go
  pkg/collect/certificates_test.go
  pkg/collect/collector.go
  schemas/collector-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::bug, bug::regression

#1204 Update the preflight secret label to troubleshoot.sh/kind
  pkg/preflight/read_specs.go
  testdata/preflightspec/troubleshoot_v1beta2_preflight_secret_gotest.yaml
  testdata/preflightspec/troubleshoot_v1beta2_preflight_secret_stringdata_gotest.yaml
Labels: type::bug, bug::normal

#1211 chore: add make target to build all binaries together
  Makefile
Labels: type::chore

#1202 feat: add loader APIs to load specs from raw troubleshoot spec
  cmd/analyze/cli/run.go
  cmd/collect/cli/run.go
  cmd/troubleshoot/cli/analyze.go
  cmd/troubleshoot/cli/interactive_results.go
  cmd/troubleshoot/cli/run.go
  internal/util/util.go
  pkg/collect/load.go
  pkg/constants/constants.go
  pkg/loader/loader.go
  pkg/loader/loader_test.go
  pkg/oci/pull.go
  pkg/preflight/interactive_results.go
  pkg/preflight/output_to_file.go
  pkg/preflight/read_specs.go
  pkg/preflight/read_specs_test.go
  pkg/preflight/run.go
  pkg/specs/specs.go
  pkg/supportbundle/load.go
  testdata/yamldocs/helm-template.yaml
  testdata/yamldocs/multidoc-spec-1.yaml
  testdata/yamldocs/multidoc-spec-2.yaml
  testdata/yamldocs/multidoc-spec-3.yaml
Labels: type::feature

#1210 Add ability for Cluster resources analyzer to do number and size comparison
  pkg/analyze/common_status.go
  pkg/analyze/kube_resource.go
  pkg/analyze/kube_resource_test.go
Labels: type::feature

#1214 chore: remove unnecessary logrus dependency
  go.mod
  pkg/longhorn/types/setting.go
  pkg/longhorn/util/iscsi.go
  pkg/longhorn/util/util.go
Labels: type::chore

#1203 feat(support-bundle): add support labels for troubleshoot.io and troubleshoot.sh
  cmd/troubleshoot/cli/root.go
  cmd/troubleshoot/cli/run.go
  docs/preflight.md
  docs/preflight_oci-fetch.md
  docs/support-bundle.md
  pkg/constants/constants.go
  pkg/specs/specs.go
  pkg/specs/specs_test.go
  test/validate-support-bundle-e2e.sh
  testdata/supportbundle/labelled-specs/redact-spec-3.yaml
  testdata/supportbundle/labelled-specs/redact-spec-4.yaml
  testdata/supportbundle/labelled-specs/sb-spec-3.yaml
  testdata/supportbundle/labelled-specs/sb-spec-4.yaml
Labels: type::bug, bug::normal

#1213 Add Daemonset collection to cluster_resources
  pkg/collect/cluster_resources.go
  pkg/constants/constants.go
Labels: type::feature

#1174 feat: add k8s custom metrics collector
  config/crds/troubleshoot.sh_collectors.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  go.mod
  go.sum
  pkg/apis/troubleshoot/v1beta2/collector_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  pkg/collect/collector.go
  pkg/collect/k8s_metrics.go
  pkg/collect/k8s_metrics_test.go
  schemas/collector-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::feature

#1219 Add code to collect cluster endpoint data with cluster-resources collector
  pkg/collect/cluster_resources.go
  pkg/constants/constants.go
Labels: type::feature

#1212 make ConfigMap collector namespace-optional
  pkg/collect/configmap.go
  testdata/supportbundle/configmaps.yaml
Labels: type::bug, bug::normal

#1196 fix(collector): solving pod stuck in terminating with CNI issue
  examples/preflight/e2e.yaml
  pkg/collect/copy_from_host.go
  pkg/collect/run_pod.go
  pkg/constants/constants.go
Labels: type::bug, bug::regression

#1222 feat(collector): checking existing service account before create running pod
  pkg/collect/run.go
  pkg/collect/runner.go
  pkg/collect/util.go
  pkg/collect/util_test.go
Labels: type::bug, bug::regression

#1226 explicitly test TCPConnectAnalyze unconditional fallthrough behavior
  pkg/analyze/host_tcp_connect_test.go
Labels: type::chore

#1104 chore: Upgrade sigstore and goreleaser binaries
  .github/workflows/build-test-deploy.yaml
  README.md
Labels: type::chore

#1227 feat: add test for HostPreflight spec read
  pkg/preflight/read_specs_test.go
Labels: type::chore

#1243 get cluster-resources even if negotiating RBAC fails
  pkg/collect/cluster_resources.go
  pkg/constants/constants.go
Labels: type::bug, bug::normal

#1242 fix(message): fix message display issue
  cmd/troubleshoot/cli/interactive_results.go
  internal/util/util.go
  pkg/constants/constants.go
  pkg/preflight/interactive_results.go
Labels: type::bug, bug::regression

#1252 feat(examples): loading troubleshoot specs from helm chart example
  .github/workflows/build-test-deploy.yaml
  Makefile
  examples/sdk/helm-template/README.md
  examples/sdk/helm-template/go.mod
  examples/sdk/helm-template/go.sum
  examples/sdk/helm-template/main.go
  examples/sdk/helm-template/mychart-0.1.0.tgz
  test/run-examples.sh
Labels: type::feature
