Repository replicatedhq/troubleshoot, pull requests merged in 2023-08, with the labels that each got.

#1297 chore: export error ErrInsufficientPermissionsToRun and func ShowTextResultsStructured
  pkg/collect/collect.go
  pkg/preflight/collect.go
  pkg/preflight/text_results.go
  pkg/supportbundle/collect.go
Labels: type::chore

#1281 Fix(support-bundle): add pod force deletion and check failedmount event for copy from host daemonset pod
  pkg/collect/collectd.go
  pkg/collect/collector.go
  pkg/collect/copy_from_host.go
  pkg/collect/copy_from_host_test.go
  pkg/constants/constants.go
Labels: type::bug, bug::regression

#1300 fix(json_compare): solve unorderd slice deep equal
  pkg/analyze/json_compare.go
  pkg/analyze/json_compare_test.go
Labels: type::bug, bug::regression

#1265 feat(e2e): add e2e go test for cluster resource
  .github/workflows/build-test-deploy.yaml
  Makefile
  go.mod
  go.sum
  test/e2e/support-bundle/cluster_pod_statuses_e2e_test.go
  test/e2e/support-bundle/cluster_resources_e2e_test.go
  test/e2e/support-bundle/main_e2e_test.go
  test/e2e/support-bundle/spec/clusterResources.yaml
  test/e2e/support-bundle/spec/pod.yaml
  test/validate-support-bundle-e2e.sh
Labels: type::feature

#1291 feat(redact): use a scan regex for default redact rule of lines to improve cpu usage and reduce time cost
  pkg/collect/redact.go
  pkg/collect/result.go
  pkg/constants/constants.go
  pkg/redact/multi_line.go
  pkg/redact/multi_line_test.go
  pkg/redact/redact.go
  pkg/redact/redact_test.go
  pkg/redact/single_line.go
  pkg/redact/single_line_test.go
Labels: type::feature

#1290 fix: complete mssql analyser implementation
  pkg/analyze/analyzer.go
  pkg/analyze/mssql.go
  pkg/analyze/mssql_test.go
  pkg/analyze/mysql.go
  pkg/collect/mssql.go
Labels: type::bug, bug::normal

#1313 chore: make spec loaders internal APIs
  cmd/troubleshoot/cli/run.go
  internal/specs/configmaps.go
  internal/specs/configmaps_test.go
  internal/specs/secrets.go
  internal/specs/secrets_test.go
  internal/specs/specs.go
  internal/specs/specs_test.go
  internal/testutils/utils.go
  pkg/loader/loader.go
  pkg/loader/loader_test.go
  pkg/logger/logger.go
  pkg/preflight/read_specs.go
  pkg/preflight/read_specs_test.go
  pkg/specs/configmaps.go
  pkg/specs/secrets.go
  pkg/specs/specs.go
  pkg/specs/specs_test.go
Labels: type::chore

#1320 Replace FOSSA with Trivy
  .fossa.yml
  .github/workflows/fossa.yaml
  .github/workflows/license.yaml
Labels: type::chore
