Repository replicatedhq/troubleshoot, pull requests merged in 2024-03, with the labels that each got.

#1497 fix panic in Velero analyzer when there's no Velero deployment found
  pkg/analyze/velero.go
Labels: type::bug, bug::regression

#1474 New Event Analyzer
  config/crds/troubleshoot.sh_analyzers.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  pkg/analyze/analyzer.go
  pkg/analyze/event.go
  pkg/analyze/event_test.go
  pkg/apis/troubleshoot/v1beta2/analyzer_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  schemas/analyzer-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::feature

#1499 fix: flaky goldpinger e2e test
  test/e2e/support-bundle/goldpinger_collector_e2e_test.go
  test/e2e/support-bundle/main_e2e_test.go
Labels: type::chore

#1501 fix: Parse v1beta1 troubleshoot specs when using loader API
  pkg/constants/constants.go
  pkg/loader/loader.go
  pkg/loader/loader_test.go
Labels: type::bug, bug::regression

#1508 Quick fix to prevent panic on nil collector result
  pkg/collect/run_pod.go
Labels: type::bug, bug::regression

#1511 New JSON field in HTTP request collector if any
  pkg/collect/http.go
  pkg/collect/http_test.go
Labels: type::feature

#1513 feat: Prompt for privileged user if host collectors present in spec
  cmd/troubleshoot/cli/run.go
  internal/util/util.go
  pkg/preflight/run.go
Labels: type::feature

#1515 chore: Update code generator and controller tools
  Makefile
  config/crds/troubleshoot.replicated.com_analyzers.yaml
  config/crds/troubleshoot.replicated.com_collectors.yaml
  config/crds/troubleshoot.replicated.com_preflights.yaml
  config/crds/troubleshoot.replicated.com_redactors.yaml
  config/crds/troubleshoot.replicated.com_supportbundles.yaml
  config/crds/troubleshoot.sh_analyzers.yaml
  config/crds/troubleshoot.sh_collectors.yaml
  config/crds/troubleshoot.sh_hostcollectors.yaml
  config/crds/troubleshoot.sh_hostpreflights.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_redactors.yaml
  config/crds/troubleshoot.sh_remotecollectors.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  pkg/apis/troubleshoot/v1beta1/zz_generated.deepcopy.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  schemas/analyzer-troubleshoot-v1beta1.json
  schemas/analyzer-troubleshoot-v1beta2.json
  schemas/collector-troubleshoot-v1beta1.json
  schemas/collector-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta1.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/redactor-troubleshoot-v1beta1.json
  schemas/redactor-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta1.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::chore

#1517 chore: Update CLI prompt to run command as root
  cmd/troubleshoot/cli/run.go
  internal/util/util.go
  pkg/preflight/run.go
Labels: type::chore
