Repository replicatedhq/troubleshoot, pull requests merged in 2024-05, with the labels that each got.

#1539 Revert "feat: URI is not replacing the spec but merging instead (#1537)
  cmd/troubleshoot/cli/run.go
  cmd/troubleshoot/cli/run_test.go
Labels: type::bug, bug::regression

#1541 feat: [sc-103119] URI is not replacing the spec but merging instead
  cmd/troubleshoot/cli/run.go
  cmd/troubleshoot/cli/run_test.go
Labels: type::feature

#1544 feat: Prefer embedded-cluster over k0s when detecting distro
  pkg/analyze/distribution.go
  pkg/analyze/distribution_test.go
Labels: type::feature

#1542 bug: [sc-103753] Host analysers are not deduplicating during multiple spec merges #1485
  cmd/troubleshoot/cli/run.go
  cmd/troubleshoot/cli/run_test.go
  internal/util/util.go
Labels: type::bug, bug::normal

#1547 feat(analyzer): let cluster resource case insensitive to fix name inconsistent
  pkg/analyze/files/support-bundle/cluster-resources/configmaps/kube-public.json
  pkg/analyze/kube_resource.go
  pkg/analyze/kube_resource_test.go
Labels: type::bug, bug::normal

#1546 feat: New host collector and analyzer for Kernel Configs
  config/crds/troubleshoot.sh_analyzers.yaml
  config/crds/troubleshoot.sh_hostcollectors.yaml
  config/crds/troubleshoot.sh_hostpreflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  pkg/analyze/host_analyzer.go
  pkg/analyze/host_kernel_configs.go
  pkg/analyze/host_kernel_configs_test.go
  pkg/apis/troubleshoot/v1beta2/hostanalyzer_shared.go
  pkg/apis/troubleshoot/v1beta2/hostcollector_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  pkg/collect/host_collector.go
  pkg/collect/host_kernel_configs.go
  pkg/collect/host_kernel_configs_test.go
  pkg/constants/constants.go
  schemas/analyzer-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::feature

#1554 fix: Use correct cron job kind when discovering API versions
  pkg/collect/cluster_resources.go
  test/e2e/support-bundle/cluster_resources_e2e_test.go
Labels: type::bug, bug::normal
