Repository replicatedhq/troubleshoot, pull requests merged in 2024-09, with the labels that each got.

#1605 feat(analyzer): allow templating for Node Resources Analyzer
  config/crds/troubleshoot.sh_analyzers.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  pkg/analyze/node_resources.go
  pkg/analyze/node_resources_test.go
  pkg/apis/troubleshoot/v1beta2/analyzer_shared.go
  schemas/analyzer-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::feature

#1606 feat: [sc-110727] troubleshoot: collector/analyzer for wildcard dns
  config/crds/troubleshoot.sh_collectors.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  pkg/apis/troubleshoot/v1beta2/collector_shared.go
  pkg/collect/dns.go
  pkg/collect/dns_test.go
  schemas/collector-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::feature

#1611 fix: --redactors flag is dropped if no spec provided
  cmd/troubleshoot/cli/run.go
  test/validate-support-bundle-e2e.sh
  testdata/supportbundle/labelled-bundle-unlabelled-redactor/redact-spec-1.yaml
  testdata/supportbundle/labelled-bundle-unlabelled-redactor/sb-spec-1.yaml
Labels: type::bug, bug::regression

#1613 fix: [sc-112114] registry collector failed to talk to Replicated private registry
  pkg/collect/registry.go
  pkg/collect/registry_test.go
Labels: type::bug, bug::normal

#1612 feat: Optionally save preflight bundles to disk
  Makefile
  cmd/preflight/cli/root.go
  cmd/troubleshoot/cli/redact.go
  cmd/troubleshoot/cli/root.go
  pkg/collect/result.go
  pkg/constants/constants.go
  pkg/preflight/collect.go
  pkg/preflight/run.go
  pkg/supportbundle/collect.go
  pkg/supportbundle/supportbundle.go
  pkg/version/version.go
  test/validate-preflight-e2e.sh
Labels: type::feature

#1617 feat: host collector for DNS
  config/crds/troubleshoot.sh_hostcollectors.yaml
  config/crds/troubleshoot.sh_hostpreflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  go.mod
  pkg/apis/troubleshoot/v1beta2/hostcollector_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  pkg/collect/dns.go
  pkg/collect/host_collector.go
  pkg/collect/host_dns.go
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::feature

#1619 feat: Install goldpinger daemonset if one does not exist when running goldpinger collector
  config/crds/troubleshoot.sh_collectors.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  pkg/analyze/goldpinger_test.go
  pkg/apis/troubleshoot/v1beta2/collector_shared.go
  pkg/collect/goldpinger.go
  schemas/collector-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
  test/e2e/support-bundle/goldpinger_collector_e2e_test.go
  testdata/charts/goldpinger-6.0.1.tgz
  testdata/goldpinger/checkall-one-pod.json
Labels: type::feature

#1618 feat(analyzer): enable host os info analyzer to support multiple nodes
  pkg/analyze/host_os_info.go
  pkg/analyze/host_os_info_test.go
  pkg/collect/collect.go
  pkg/collect/host_os_info.go
  test/e2e/support-bundle/hostOS_remote_collector_e2e_test.go
Labels: type::feature

#1626 bug: Remove duplicate results in preflights
  pkg/analyze/analyzer.go
  pkg/analyze/distribution.go
  pkg/preflight/analyze.go
  pkg/preflight/run.go
Labels: type::bug, bug::regression

#1628 feat: add CPU micro architecture support
  pkg/analyze/host_cpu.go
  pkg/analyze/host_cpu_test.go
  pkg/collect/host_cpu.go
  pkg/collect/host_cpu_test.go
Labels: type::feature

#1629 change resolvedFromSearch content
  pkg/collect/host_dns.go
  pkg/collect/host_dns_test.go
Labels: type::feature, type::chore
