Repository replicatedhq/troubleshoot, pull requests merged in 2024-01, with the labels that each got.

#1418 fix (supportbundle): Add default collectors when expected
  cmd/troubleshoot/cli/run.go
  cmd/troubleshoot/cli/run_test.go
  internal/testutils/utils.go
  internal/util/util.go
  pkg/supportbundle/supportbundle.go
Labels: type::bug, bug::regression

#1419 bump k8s.io packages to v0.29.0
  .github/workflows/build-test-deploy.yaml
  .github/workflows/license.yaml
  config/crds/troubleshoot.sh_collectors.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  go.mod
  go.sum
  pkg/collect/mssql.go
  schemas/collector-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::chore

#1402 feat: [ISSUE-1401]: Added helm get values option in Helm collector
  config/crds/troubleshoot.sh_collectors.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  pkg/apis/troubleshoot/v1beta2/collector_shared.go
  pkg/collect/helm.go
  schemas/collector-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
  test/e2e/support-bundle/helm_collector_e2e_test.go
  test/e2e/support-bundle/spec/helm.yaml
  test/e2e/support-bundle/testdata/helm-values.yaml
Labels: type::feature

#1433 chore: minor updates to docs and Makefile
  .golangci.yaml
  CONTRIBUTING.md
  Makefile
  docs/preflight.md
  docs/preflight_oci-fetch.md
  docs/preflight_version.md
  docs/support-bundle.md
  docs/support-bundle_analyze.md
  docs/support-bundle_redact.md
  docs/support-bundle_version.md
Labels: type::chore

#1432 feat: Allow templating of outcome messages for the JSON/YAML compare analyzers
  Makefile
  internal/util/util.go
  internal/util/util_test.go
  pkg/analyze/json_compare.go
  pkg/analyze/json_compare_test.go
  pkg/analyze/yaml_compare.go
  pkg/analyze/yaml_compare_test.go
Labels: type::feature

#1435 feat: add timeout to run host collector
  config/crds/troubleshoot.sh_hostcollectors.yaml
  config/crds/troubleshoot.sh_hostpreflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  pkg/apis/troubleshoot/v1beta2/hostcollector_shared.go
  pkg/collect/host_run.go
  pkg/collect/host_run_test.go
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::feature
