Repository replicatedhq/troubleshoot, pull requests merged in 2024-02, with the labels that each got.

#1445 bump containerd to patch for CVE-2024-21626
  go.mod
  go.sum
Labels: type::chore

#1449 Add workaround for EKS version string
  pkg/analyze/cluster_version.go
  pkg/analyze/cluster_version_test.go
Labels: type::feature

#1450 chore: additional ceph collector commands
  pkg/collect/ceph.go
Labels: type::chore

#1458 Revert "chore(deps): bump github.com/vmware-tanzu/velero from 1.12.0 to 1.13.0"
  go.mod
  go.sum
Labels: type::chore

#1456 fix: Correct selector used to find installer specs when redacting
  Makefile
  pkg/redact/redact.go
  pkg/redact/yaml.go
Labels: type::bug, bug::normal

#1461 update correct K8S API group for batch and policy
  pkg/collect/cluster_resources.go
Labels: type::bug, bug::normal

#1463 fix: improve flaky goldpinger test
  test/e2e/support-bundle/goldpinger_collector_e2e_test.go
Labels: type::bug, bug::regression

#1469 feat: sonobuoy collector
  Makefile
  config/crds/troubleshoot.sh_collectors.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  pkg/apis/troubleshoot/v1beta2/collector_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  pkg/collect/collector.go
  pkg/collect/sonobuoy_results.go
  schemas/collector-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
  test/e2e/support-bundle/main_e2e_test.go
  test/e2e/support-bundle/sonobuoy_e2e_test.go
  test/e2e/support-bundle/spec/sonobuoy.yaml
Labels: type::feature

#1477 Update dependabot.yml
  .github/dependabot.yml
Labels: type::chore

#1481 update Helm example for CVE
  examples/sdk/helm-template/go.mod
  examples/sdk/helm-template/go.sum
Labels: type::chore

#1482 Update dependabot.yml
  .github/dependabot.yml
Labels: type::chore

#1473 feat: add dependabot auto merge
  .github/CODEOWNERS
  .github/workflows/automated-prs-manager.yaml
  .github/workflows/build-test-deploy.yaml
Labels: type::feature

#1489 Fix automated PRs manager workflow
  .github/workflows/automated-prs-manager.yaml
  pkg/collect/certificates_test.go
  pkg/collect/host_certificates_collection_test.go
Labels: type::security

#1491 Fix workflow name in automated PRs manager
  .github/workflows/automated-prs-manager.yaml
  .github/workflows/build-test-deploy.yaml
Labels: type::security

#1493 Add delay between approving and merging PR in the automated PRs manager
  .github/workflows/automated-prs-manager.yaml
Labels: type::security
