Repository replicatedhq/troubleshoot, pull requests merged in 2024-04, with the labels that each got.

#1516 feat: node metrics collector
  Makefile
  config/crds/troubleshoot.sh_collectors.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  pkg/apis/troubleshoot/v1beta2/collector_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  pkg/collect/collector.go
  pkg/collect/k8s_node_metrics.go
  pkg/collect/k8s_node_metrics_test.go
  pkg/collect/redact.go
  pkg/collect/result.go
  schemas/collector-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::feature

#1521 feat: distribution analyzer support for kind
  examples/preflight/sample-preflight.yaml
  pkg/analyze/distribution.go
  pkg/analyze/distribution_test.go
Labels: type::feature

#1520 feat: node metrics analyser
  config/crds/troubleshoot.sh_analyzers.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  go.mod
  go.sum
  pkg/analyze/analyzer.go
  pkg/analyze/comparison.go
  pkg/analyze/comparison_test.go
  pkg/analyze/k8s_node_metrics.go
  pkg/analyze/k8s_node_metrics_test.go
  pkg/apis/troubleshoot/v1beta2/analyzer_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  pkg/preflight/flags.go
  schemas/analyzer-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
  test/e2e/support-bundle/goldpinger_collector_e2e_test.go
Labels: type::feature

#1528 update k8s imports to v0.30.0 and address changed function signature
  config/crds/troubleshoot.sh_collectors.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  examples/sdk/helm-template/go.mod
  examples/sdk/helm-template/go.sum
  go.mod
  go.sum
  pkg/collect/host_network.go
  schemas/collector-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::chore

#1529 feat: Detect EC as a distribution
  docs/design/proposal-standard-interface.md
  pkg/analyze/distribution.go
  pkg/analyze/distribution_test.go
Labels: type::feature

#1535 fix(collector): fix helm collector with a nil error return to error list
  pkg/collect/helm.go
Labels: type::bug, bug::normal

#1537 feat: [sc-103119] URI is not replacing the spec but merging instead
  cmd/troubleshoot/cli/run.go
  cmd/troubleshoot/cli/run_test.go
Labels: type::bug, bug::normal

#1538 feat(analyzer): make sure ReplicaSetStatus has valid result
  pkg/analyze/replicaset_status.go
Labels: type::bug, bug::normal

#1534 feat: [sc-103754] Be able to detect search domain misconfiguration #1391
  config/crds/troubleshoot.sh_collectors.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  pkg/apis/troubleshoot/v1beta2/collector_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  pkg/collect/collector.go
  pkg/collect/dns.go
  pkg/collect/dns_test.go
  schemas/collector-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::feature
