Repository replicatedhq/troubleshoot, pull requests merged in 2024-11, with the labels that each got.

#1667 feat: multiple nodes analyzers
  pkg/analyze/collected_contents.go
  pkg/analyze/host_analyzer.go
  pkg/analyze/host_analyzer_test.go
  pkg/analyze/host_block_devices.go
  pkg/analyze/host_certificate.go
  pkg/analyze/host_disk_usage.go
  pkg/analyze/host_filesystem_performance.go
  pkg/analyze/host_http.go
  pkg/analyze/host_httploadbalancer.go
  pkg/analyze/host_httploadbalancer_test.go
  pkg/analyze/host_ipv4interfaces.go
  pkg/analyze/host_kernel_configs.go
  pkg/analyze/host_memory.go
  pkg/analyze/host_os_info.go
  pkg/analyze/host_services.go
  pkg/analyze/host_subnetavailable.go
  pkg/analyze/host_subnetavailable_test.go
  pkg/analyze/host_system_packages.go
  pkg/analyze/host_tcp_connect.go
  pkg/analyze/host_tcploadbalancer.go
  pkg/analyze/host_tcpportstatus.go
  pkg/analyze/host_time.go
  pkg/analyze/host_time_test.go
  pkg/analyze/host_udpportstatus.go
  pkg/collect/host_block_device.go
  pkg/collect/host_ipv4interfaces.go
  pkg/collect/host_kernel_configs.go
  pkg/collect/host_services.go
  pkg/collect/host_time.go
Labels: type::feature

#1664 chore: Refactor host cpu analyzer for remote collection
  pkg/analyze/host_cpu.go
  pkg/collect/host_cpu.go
Labels: type::chore

#1670 feat: implement collector and analyser for network namespace connectivity
  config/crds/troubleshoot.sh_analyzers.yaml
  config/crds/troubleshoot.sh_collectors.yaml
  config/crds/troubleshoot.sh_hostcollectors.yaml
  config/crds/troubleshoot.sh_hostpreflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  go.mod
  go.sum
  pkg/analyze/host_analyzer.go
  pkg/analyze/host_network_namespace_connectivity.go
  pkg/apis/troubleshoot/v1beta2/hostanalyzer_shared.go
  pkg/apis/troubleshoot/v1beta2/hostcollector_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  pkg/collect/host_collector.go
  pkg/collect/host_network_namespace_connectivity.go
  pkg/namespaces/errors.go
  pkg/namespaces/errors_test.go
  pkg/namespaces/interface-pair.go
  pkg/namespaces/interface-pair_test.go
  pkg/namespaces/managed-namespace.go
  pkg/namespaces/managed-namespace_unsupported.go
  pkg/namespaces/namespace-handler.go
  pkg/namespaces/namespace-pinger.go
  pkg/namespaces/netlink-handler.go
  pkg/namespaces/network-namespace.go
  pkg/namespaces/network-namespace_test.go
  pkg/namespaces/options.go
  schemas/analyzer-troubleshoot-v1beta2.json
  schemas/collector-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::feature

#1672 Fix remote host collection RBAC checks
  pkg/supportbundle/collect.go
  pkg/supportbundle/rbac.go
  pkg/supportbundle/supportbundle.go
Labels: type::bug, bug::normal

#1676 feat(host_sysctl): add host sysctl collector
  config/crds/troubleshoot.sh_collectors.yaml
  config/crds/troubleshoot.sh_hostcollectors.yaml
  config/crds/troubleshoot.sh_hostpreflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  examples/collect/host/sysctl.yaml
  examples/preflight/host/sysctl.yaml
  pkg/apis/troubleshoot/v1beta2/hostcollector_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  pkg/collect/host_collector.go
  pkg/collect/host_sysctl.go
  pkg/collect/host_sysctl_test.go
  schemas/collector-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::feature

#1678 fix: Do not fail analysis if node list does not exist
  pkg/analyze/collected_contents.go
  pkg/analyze/collected_contents_test.go
  pkg/supportbundle/parse.go
Labels: type::bug, bug::regression

#1680 feat(e2e): add local host support bundle test
  .github/workflows/build-test-deploy.yaml
  test/e2e/preflight/host_local_collector_e2e_test.go
  test/e2e/preflight/main_e2e_test.go
  test/e2e/preflight/spec/localHostCollectors.yaml
  test/e2e/support-bundle/host_local_collector_e2e_test.go
  test/e2e/support-bundle/spec/localHostCollectors.yaml
Labels: type::feature

#1677 remove redundant tests
  .github/workflows/build-test-deploy.yaml
  Makefile
Labels: type::chore

#1681 feat(host_analyzer): add host sysctl analyzer
  config/crds/troubleshoot.sh_analyzers.yaml
  config/crds/troubleshoot.sh_hostcollectors.yaml
  config/crds/troubleshoot.sh_hostpreflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  examples/preflight/host/sysctl.yaml
  pkg/analyze/host_analyzer.go
  pkg/analyze/host_sysctl.go
  pkg/analyze/host_sysctl_test.go
  pkg/analyze/host_time.go
  pkg/apis/troubleshoot/v1beta2/hostanalyzer_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  pkg/collect/host_sysctl.go
  schemas/analyzer-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
  test/e2e/support-bundle/host_local_collector_e2e_test.go
  test/e2e/support-bundle/spec/localHostCollectors.yaml
  test/e2e/support-bundle/spec/remoteHostCollectors.yaml
Labels: type::feature

#1671 exec remote host collectors in a daemonset
  pkg/supportbundle/collect.go
  test/e2e/support-bundle/host_remote_collector_e2e_test.go
Labels: type::feature

#1686 feat: [sc-114709] [troubleshoot] gracefully handle inability to load specs if multiple specs provided
  internal/specs/specs.go
  internal/specs/specs_test.go
Labels: type::feature

#1687 fix(analyzer): add missing warning in outcome
  pkg/analyze/text_analyze.go
  pkg/analyze/text_analyze_test.go
Labels: type::bug, bug::normal

#1688 feat: ensure Copy collector run last
  pkg/collect/collector.go
  pkg/collect/collector_test.go
  pkg/preflight/collect.go
  pkg/supportbundle/collect.go
Labels: type::feature

#1690 fix(collector): fix dns collector limited to 63 chars
  pkg/collect/host_network.go
  pkg/collect/host_network_test.go
Labels: type::bug, bug::normal

#1693 feat: rename templating variables
  pkg/collect/host_network_namespace_connectivity.go
Labels: type::feature

#1695 [bug] Quick fix for handling non 200 status codes when loading specs from URI
  pkg/supportbundle/load.go
Labels: type::bug, bug::normal

#1697 feat: add support for matchExpressions when filtering for nodes
  config/crds/troubleshoot.sh_analyzers.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  pkg/analyze/node_resources.go
  pkg/analyze/node_resources_test.go
  pkg/apis/troubleshoot/v1beta2/analyzer_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  schemas/analyzer-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::feature
