Repository replicatedhq/troubleshoot, pull requests merged in 2024-10, with the labels that each got.

#1632 feat: [sc-113128] Create node list file before running remote host collector
  pkg/analyze/host_os_info.go
  pkg/collect/collect.go
  pkg/collect/host_os_info.go
  pkg/constants/constants.go
  pkg/supportbundle/supportbundle.go
  pkg/supportbundle/supportbundle_test.go
Labels: type::feature

#1631 feat: allow users to check cpu flags
  pkg/analyze/host_cpu.go
  pkg/analyze/host_cpu_test.go
Labels: type::feature

#1635 Allow goldpinger / goldpinger util images to be set in collector spec
  config/crds/troubleshoot.sh_collectors.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  pkg/apis/troubleshoot/v1beta2/collector_shared.go
  pkg/collect/goldpinger.go
  schemas/collector-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
Labels: type::feature

#1636 chore: Collect endpointslices resources
  pkg/collect/cluster_resources.go
  pkg/constants/constants.go
Labels: type::chore

#1633 Refactor Remote Host Collection
  cmd/troubleshoot/cli/run.go
  config/crds/troubleshoot.sh_supportbundles.yaml
  pkg/apis/troubleshoot/v1beta2/remote_collector_shared.go
  pkg/apis/troubleshoot/v1beta2/supportbundle_types.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/fake/fake_supportbundle.go
  pkg/client/troubleshootclientset/typed/troubleshoot/v1beta2/supportbundle.go
  pkg/collect/cluster_resources_test.go
  pkg/collect/host_collector.go
  pkg/collect/host_collector_test.go
  pkg/collect/host_os_info.go
  pkg/loader/loader_test.go
  pkg/supportbundle/collect.go
  pkg/supportbundle/load.go
  pkg/supportbundle/rbac.go
  schemas/supportbundle-troubleshoot-v1beta2.json
  test/e2e/support-bundle/host_remote_collector_e2e_test.go
  test/e2e/support-bundle/spec/hostOSRemoteCollector.yaml
  test/e2e/support-bundle/spec/remoteHostCollectors.yaml
  testdata/yamldocs/helm-template.yaml
Labels: type::feature

#1645 chore: Explicitly run make lint
  .github/workflows/build-test-deploy.yaml
  .github/workflows/license.yaml
  .golangci.yaml
  Makefile
Labels: type::chore

#1644 feat: allow users to check cpu arch
  pkg/analyze/host_cpu.go
  pkg/analyze/host_cpu_test.go
  pkg/collect/host_cpu.go
  pkg/collect/host_cpu_test.go
Labels: type::feature

#1634 chore(support-bundle): respect using load-cluster-specs=false
  cmd/troubleshoot/cli/root.go
  cmd/troubleshoot/cli/run.go
  internal/specs/specs.go
  pkg/loader/loader.go
  pkg/types/types.go
Labels: type::chore

#1647 fix: [sc-111255] CRD analyzer outcomes has no Warn field
  pkg/analyze/crd.go
  pkg/analyze/crd_test.go
Labels: type::feature

#1651 fix(make): make sure github action can check schemas change
  .github/workflows/build-test-deploy.yaml
  Makefile
Labels: type::bug, bug::normal

#1653 bug: fix nil check in host collector filter
  pkg/supportbundle/collect.go
  pkg/supportbundle/collect_test.go
Labels: type::bug, bug::normal

#1655 chore: Remove preempted deprecation warnings
  go.mod
  pkg/supportbundle/load.go
Labels: type::chore

#1646 Refactor Multi Node Analyzers
  pkg/analyze/collected_contents.go
  pkg/analyze/collected_contents_test.go
  pkg/analyze/host_analyzer.go
  pkg/analyze/host_analyzer_test.go
  pkg/analyze/host_memory.go
  pkg/analyze/host_memory_test.go
  pkg/analyze/host_os_info.go
  pkg/analyze/host_os_info_test.go
  pkg/collect/host_memory.go
  pkg/supportbundle/collect.go
  pkg/supportbundle/collect_test.go
Labels: type::chore

#1656 fix(support): add missing host collectors for ParseSupportBundle
  config/crds/troubleshoot.sh_collectors.yaml
  pkg/apis/troubleshoot/v1beta2/collector_types.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  pkg/supportbundle/load.go
  pkg/supportbundle/load_test.go
  schemas/collector-troubleshoot-v1beta2.json
Labels: type::bug, bug::normal

#1657 [collect] accept stdin
  cmd/collect/cli/run.go
Labels: type::feature

#1654 fix: update feature epic proposal template
  .github/ISSUE_TEMPLATE/feature_epic.md
Labels: type::chore

#1660 feat: Handle failure to load cluster specs gracefully in support-bundle command
  internal/specs/specs.go
Labels: type::feature

#1624 support adding a CA cert to http collector
  .golangci.yaml
  config/crds/troubleshoot.sh_collectors.yaml
  config/crds/troubleshoot.sh_hostcollectors.yaml
  config/crds/troubleshoot.sh_hostpreflights.yaml
  config/crds/troubleshoot.sh_preflights.yaml
  config/crds/troubleshoot.sh_remotecollectors.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  go.mod
  pkg/apis/troubleshoot/v1beta2/collector_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  pkg/collect/host_http.go
  pkg/collect/http.go
  pkg/collect/http_test.go
  schemas/collector-troubleshoot-v1beta2.json
  schemas/preflight-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
  testdata/https-proxy-replicated-app.yaml
Labels: type::feature, echoes/effort: M

#1659 feat(host-collector): add progress for host collector
  pkg/supportbundle/collect.go
Labels: type::feature

#1662 feat: Do not prompt users to save support bundle analysis results
  cmd/troubleshoot/cli/interactive_results.go
  pkg/preflight/interactive_results.go
Labels: type::feature

#1668 fix(collector): limit run pod collector to delete only one related secret
  pkg/collect/run_pod.go
Labels: type::bug, bug::normal

#1669 [sc-114813] copy HostCollector fails to copy binary files when run in cluster
  pkg/collect/runner.go
Labels: type::bug, bug::normal
