Repository replicatedhq/troubleshoot, pull requests merged in 2025-02, with the labels that each got.

#1729 Enable Daemonsets in ClusterResources analyzer
  pkg/analyze/kube_resource.go
Labels: type::feature

#1728 fix(window): improve rename file process and remove windows release
  .github/workflows/build-test-deploy.yaml
  deploy/krew/preflight.yaml
  deploy/krew/support-bundle.yaml
  internal/util/util.go
  internal/util/util_test.go
  pkg/collect/redact.go
  pkg/collect/result.go
  pkg/longhorn/util/iscsi_windows.go
Labels: type::bug, bug::normal

#1733 chore: updates to make targets for building binaries
  Makefile
Labels: type::chore

#1735 Add a host analyzer to check if a subnet contains an IP address
  config/crds/troubleshoot.sh_analyzers.yaml
  config/crds/troubleshoot.sh_hostcollectors.yaml
  config/crds/troubleshoot.sh_hostpreflights.yaml
  config/crds/troubleshoot.sh_supportbundles.yaml
  examples/preflight/host/subnet-contains-ip.yaml
  pkg/analyze/host_analyzer.go
  pkg/analyze/host_subnetcontainsip.go
  pkg/analyze/host_subnetcontainsip_test.go
  pkg/apis/troubleshoot/v1beta2/hostanalyzer_shared.go
  pkg/apis/troubleshoot/v1beta2/zz_generated.deepcopy.go
  pkg/collect/remote_collector.go
  schemas/analyzer-troubleshoot-v1beta2.json
  schemas/supportbundle-troubleshoot-v1beta2.json
Labels: type::feature

#1736 fix(ci): remove windows build from goreleaser
  deploy/.goreleaser.yaml
  pkg/longhorn/util/iscsi_windows.go
Labels: type::chore

#1737 fix(preflights): support for builtin kernel modules
  pkg/collect/host_kernel_modules.go
  pkg/collect/host_kernel_modules_test.go
Labels: type::bug, bug::normal

#1738 fix(preflights): builtin kernel modules file may be not found
  pkg/collect/host_kernel_modules.go
Labels: type::bug, bug::regression

#1741 fix(host-preflights): builtin kernel modules file from wrong path
  pkg/collect/host_collector.go
  pkg/collect/host_kernel_modules.go
  pkg/collect/host_kernel_modules_test.go
Labels: type::bug, bug::normal

#1744 update shirou/gopsutil to v4
  go.mod
  go.sum
  pkg/collect/host_cpu.go
  pkg/collect/host_disk_usage.go
  pkg/collect/host_memory.go
  pkg/collect/host_os_info.go
Labels: type::chore

#1742 fix(redact): multi-line redactors strip empty lines
  pkg/redact/multi_line.go
  pkg/redact/multi_line_test.go
  pkg/redact/single_line_test.go
Labels: type::bug, bug::normal

#1745 Ability to use sprig functions in analyzer templates
  internal/util/util.go
  internal/util/util_test.go
  pkg/analyze/cluster_container_statuses.go
  pkg/analyze/cluster_pod_statuses.go
  pkg/analyze/event.go
  pkg/analyze/host_filesystem_performance.go
  pkg/analyze/host_system_packages.go
  pkg/analyze/k8s_node_metrics.go
  pkg/analyze/text_analyze.go
Labels: type::feature
