Repository replicatedhq/troubleshoot, pull requests merged in 2025-03, with the labels that each got.

#1753 Http comperators
  go.mod
  go.sum
  pkg/analyze/host_http.go
  pkg/analyze/host_http_test.go
Labels: type::feature, customer-requested

#1754 add additional test cases to the host os info analyzer
  examples/sdk/helm-template/go.mod
  examples/sdk/helm-template/go.sum
  pkg/analyze/host_os_info_test.go
Labels: type::chore

#1752 Updating the cosign library for Github Actions
  .github/workflows/build-test-deploy.yaml
  Makefile
Labels: type::chore

#1756 Remove the hard coding of the cosign release [sc-77445]
  .github/workflows/build-test-deploy.yaml
Labels: type::chore

#1760 Handling the case when the Cluster Analyzer doesn't find a resource
  pkg/analyze/files/support-bundle/cluster-resources/namespaces.json
  pkg/analyze/kube_resource.go
  pkg/analyze/kube_resource_test.go
Labels: type::bug, bug::normal

#1761 fix(collect.runPod): does not delete image pull secrets without name in spec
  pkg/collect/run_pod.go
  pkg/collect/run_pod_test.go
Labels: type::bug, bug::normal
