Repository replicatedhq/troubleshoot, pull requests merged in 2025-09, with the labels that each got.

#1836 Update Claude agents and commands
  .claude/.manifest
  .claude/agents/architecture-patterns.md
  .claude/agents/ci-developer.md
  .claude/agents/codebase-analyzer.md
  .claude/agents/codebase-locator.md
  .claude/agents/codebase-pattern-finder.md
  .claude/agents/frontend-developer.md
  .claude/agents/go-developer.md
  .claude/agents/project-builder.md
  .claude/agents/proposal-needed.md
  .claude/agents/proposal-writer.md
  .claude/agents/proposals-analyzer.md
  .claude/agents/proposals-locator.md
  .claude/agents/researcher.md
  .claude/agents/shortcut.md
  .claude/agents/testing.md
  .claude/agents/web-search-researcher.md
  .claude/commands/implement.md
  .claude/commands/proposal.md
Labels: type::chore, claude-agent-sync

#1842 chore(deps): bump the security group across 1 directory with 13 updates
  go.mod
  go.sum
Labels: type::chore

#1846 fix(collect): add context timeout to registry collector
  pkg/collect/registry.go
  pkg/collect/registry_test.go
Labels: type::bug, bug::normal

#1847 Preflight docs and template subcommands
  .gitignore
  cmd/preflight/cli/docs.go
  cmd/preflight/cli/root.go
  cmd/preflight/cli/template.go
  docs/preflight.md
  docs/preflight_docs.md
  docs/preflight_template.md
  pkg/preflight/helm_renderer.go
  pkg/preflight/template.go
  sample-preflight-templated.yaml
  values-sample-full.yaml
  values-sample-minimal.yaml
Labels: type::feature

#1860 Auto support bundle upload
  cmd/troubleshoot/cli/root.go
  cmd/troubleshoot/cli/run.go
  cmd/troubleshoot/cli/upload.go
  pkg/supportbundle/extract_license.go
  pkg/supportbundle/upload.go
Labels: type::feature

#1871 Fixing testing errors
  cmd/troubleshoot/cli/diff_test.go
  cmd/troubleshoot/cli/run_test.go
Labels: type::feature

#1865 Fix/exec textanalyze path clean
  pkg/analyze/text_analyze.go
  pkg/analyze/text_analyze_test.go
Labels: type::feature

#1862 Cron job clean
  .gitignore
  Cron-Job-Support-Bundles-PRD.md
  cmd/troubleshoot/cli/root.go
  cmd/troubleshoot/cli/schedule.go
  examples/sdk/helm-template/go.mod
  examples/sdk/helm-template/go.sum
  go.mod
  go.sum
  pkg/schedule/cli.go
  pkg/schedule/daemon.go
  pkg/schedule/job.go
  pkg/schedule/schedule_test.go
  roadmap.md
  scheduled-job-daemon-explained.md
Labels: type::feature
